### ISSUE TITLE
Cannot remove an item by programming

### ISSUE THREAD

**Issue by tdhung80** [bootstrap-tagsinput/bootstrap-tagsinput#11]
hi,

When item is an object, i cannot remove it from the tagsinput. I have checked the source code, it is trying to find item by "$(this).data("item) === item", but it failed if item is an object.

I suggest you should look for value to remove associated item.

My Best,
Hung Tran

**Comment by michaelDotco2** [comment]
I had a similar problem, the item variable was a number but wasn't removing the item.
However i found it worked with JSON.stringify(item);
