### ISSUE TITLE
Troubles installing package via github url and tag

### ISSUE THREAD

**Issue by dvinci-klfr** [bootstrap-tagsinput/bootstrap-tagsinput#12]
Hello,

something happend yesterday. I have troubles installing this package via tag:

`"bootstrap-tagsinput": "git@github.com:bootstrap-tagsinput/bootstrap-tagsinput#0.8.0"`
or
`"bootstrap-tagsinput": "https://github.com/bootstrap-tagsinput/bootstrap-tagsinput.git#0.8.0",`

yarn can not resolve it:
![image](https://user-images.githubusercontent.com/56021928/161945782-c4bd2706-31ba-43cc-9d1a-7c54c164536d.png)

**Comment by filipkappa** [comment]
We're aware of this, it's a problem with missing releases, this should be resolved next week. Stay tuned!
