### ISSUE TITLE
not working with dynamic text-input

### ISSUE THREAD

**Issue by softvar** [bootstrap-tagsinput/bootstrap-tagsinput#133]
Everything works fine, even the typeahead.js after little tweaks.
But the problem is with **dynamic text-input**. The plugin doesn't seem to work with the text-inputs [no enter-effect, no tag-creation, only normal inputting text] that were dynamically created.

What's the workaround? I have done a lot using this plugin and now its annoying me just because of this issue.

**Comment by scottwarren** [comment]
Massive bump but: #271 seems to have the resolution for anyone finding this like me today :+1:

**Comment by LordRampantHump** [comment]
old i know but i faced this problem today so every time i created a new dynamic input I called the function to initialize the plugin like so:

` 
$('#preview').append('<input data-role="tagsinput" class="preview_input" type="text" id="input" placeholder="Enter Triggers"/>');
$('.preview_input').tagsinput({
    	allowDuplicates: false
    });`

this is working fine for me
