### ISSUE TITLE
trigger removeAll on form reset event

### ISSUE THREAD

**Issue by gdibble** [bootstrap-tagsinput/bootstrap-tagsinput#204]
pretty self-explanatory :wink:

**Comment by adriennn** [comment]
In the current code (0.4.3), `removeAll` doesn't 'reset'. It also gets rids of all the options set upon creation of the tagsinput, so you'd have to create the whole element again after each reset.

But +1 for a way to actually remove the tags only or a way to use a regex in the `remove` method.
