### ISSUE TITLE
itemAdded also called on initial population

### ISSUE THREAD

**Issue by toby78** [bootstrap-tagsinput/bootstrap-tagsinput#207]
the itemAdded event is also called when populating an input with existing values (added using .tagsinput('add')

**Comment by JeremyCrookshank** [comment]
Incase anyone encounters the same my version seemed to be missing this. Adding this in fixed it:

https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/commit/87a54586cba5c20ca4825dc885f87f0c34afb04a

**Comment by bhargavaaaa** [comment]
I am also facing that same problem while initializing the tagsinput
