### ISSUE TITLE
How to handle typeahead.js events properly?

### ISSUE THREAD

**Issue by kafeltz** [bootstrap-tagsinput/bootstrap-tagsinput#218]
I'm not able to handle these events properly.
https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#custom-events

I had to hack the source code to this simple line:

function TagsInput(element, options) {
   // code omited for readability
    **return this;** _// this was added to expose the object_
}

Now i can access the object and add on() method like this:

myObject = $('.typeahead').tagsinput({});

myObject[0].$input.on('typeahead:opened', function(e) { console.log('Hi!'); });

And this "patch" works fine or... i had to fallback to $(document).on() stuff that i don't like.

Sugestion: expose the typeahead so we can add on() handlers.

**Comment by merodriguezblanco** [comment]
Hi @kafeltz , you can get access to those custom events by accessing the typeahead input:

```javascript
var $input = $('.typeahead').tagsinput('input');
$input.on('typeahead:opened', function (event) {
  console.log('Hi!');
});
```

You can find that option [here](http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/#methods).
