### ISSUE TITLE
not delete text input beforeItemAdd

### ISSUE THREAD

**Issue by Mafuclero** [bootstrap-tagsinput/bootstrap-tagsinput#230]
Hi:
I'm trying to validate electronic mail beforeItemAdd but when change the value to true clears the input text is a way that does not erase.

**Comment by thedailynathan** [comment]
+1 on this... writing validation in the beforeItemAdd is very easy but it's a little infuriating that the text is forced to clear. Looking at the code the val('') is always called after the add (and afer all itemAdded events). Stichoza's hack works sort of (hard-coded time delays are always unreliable), but it would be really great if the val('') was not called if the e.cancel=true was set in the beforeItemAdd.

**Comment by Sentence** [comment]
From #250 @neverfox's answer was helped for me. Thanks again!

Simply patch the `bootstrap-tagsinput.js` then works.

My code:
(Container's has `tags` class for easy direct selecting the input.)

`$('.tags').first('input').on('beforeItemAdd', function(event) {
        event.item = event.item.replace(/[^0-9a-z-A-Z-]/g, "");
});`

**Comment by yoursakshit** [comment]
Found the solution on Stackoverflow: https://stackoverflow.com/a/36276912/2781096

use `event.cancel` property.

> $('input').on('beforeItemAdd', function(event) {
>      // Apply validation
>        if(myvalidation)
>        {
>         event.cancel = false;
>        }
>        else
>        {
>         event.cancel = true;
>        }
>    });
