### ISSUE TITLE
Typeahead text input value reappears after adding tag

### ISSUE THREAD

**Issue by hakanderyal** [bootstrap-tagsinput/bootstrap-tagsinput#236]
On the examples: https://timschlechter.github.io/bootstrap-tagsinput/examples/

In the typeahead section:
- add a tag that is not in the typeahead default list,
- do any of the following: (press esc) (press left key) (click outside of the textbox)
- the text of the added tag appears in the input field.

**Comment by sirtordo** [comment]
@itsprdp  you are the best!

**Comment by fewspider** [comment]
@itsprdp thanks a lot

**Comment by xplicit** [comment]
For bootstrap3-typeahead `self.$input.typeahead('val', '');` does not work for me, because it prevents value from duplicating by generating JS error on the page.

I use the following

	$("#elem").tagsinput({
		typeahead: {
			afterSelect: function(val) { this.$element.val(""); },
	    	source: function(query) {
				return $.get("/someurl");
	     	}
		}
	});

**Comment by snyper3xs** [comment]
@xplicit OMG thanks!

**Comment by btafoya** [comment]
@xplicit +1 Thanks!!!

**Comment by FelipeGangrel** [comment]
@xplicit You saved my bacon

**Comment by alfredopacino** [comment]
thanks xplicit, materialize-tags have the same issue

**Comment by abhaykantnirala15** [comment]
I am using 
$('input#having-skills-eidt').tagsinput('add', 'some value');
but every time it appended.
I want to reset the tagsinput before add some value
how can I reset its value?

**Comment by abhaykantnirala15** [comment]
after some research I got solution

$('#having-skills-eidt').tagsinput('removeAll');

**Comment by MyoMinLin** [comment]
Thanks a lot @itsprdp 
Your solution solved my issue also.

**Comment by mongS2** [comment]
> A better way to clear the typeahead input after adding the tag.
> 
> `self.$input.typeahead('val', '');`
> 
> Add this line to the end of the add() function after line number 149 in the src file https://github.com/TimSchlechter/bootstrap-tagsinput/blob/master/src/bootstrap-tagsinput.js
> 
> Ref: [twitter/typeahead.js#233](https://github.com/twitter/typeahead.js/issues/233)

Thanks! It works for me exactly.
