### ISSUE TITLE
id selector is not working!

### ISSUE THREAD

**Issue by gaohuasheng** [bootstrap-tagsinput/bootstrap-tagsinput#238]
When I use id to find input,for example  input id="test" type="text" data-role="tagsinput" .but $('#text').tagsinput({maxTags : 5}) not working.No matter I do anything.When I change $('#text').tagsinput({maxTags : 5}) into $('input').tagsinput({maxTags : 5}) , then it works. If one page has many inputs , this way doesn't solve it.Please help!

**Comment by thomasgallagher** [comment]
I am getting the same, doesn't work with a CSS id or class.

It does work with a custom HTML tag:
<anything></anything>
$('anything').tagsinput({maxTags : 5});

Clearly this is invalid though and means you cannot make a <select multiple>.

**Comment by mbabineau** [comment]
Janky solution. Worked for me but YMMV:
```javascript
$('#myId').first('input').tagsinput({
    typeahead: {
        source: ["Foo", "Bar", "Baz"]
    }
});
```
