### ISSUE TITLE
The "itemRemoved" event and index of removed element

### ISSUE THREAD

**Issue by SylvainCorlay** [bootstrap-tagsinput/bootstrap-tagsinput#249]
The `itemRemoved` event only holds the value of the item that was removed, but not its index. This would be useful in the case of when duplicates are allowed (`allow_duplicates == true`).

**Comment by nunaram** [comment]
Is there any solution? How to get the index?

**Comment by SylvainCorlay** [comment]
Not to my knowledge.

**Comment by nunaram** [comment]
I got the solution, it may help. 

$('input').on('beforeItemRemove', function (event) {
	var tags= $(this).tagsinput('items');
	var keyword = event.item;
	var i= tags.indexOf(keyword);
	console.log(i)
});
