### ISSUE TITLE
Issue with tags along with Typeahead 

### ISSUE THREAD

**Issue by Thileepan** [bootstrap-tagsinput/bootstrap-tagsinput#252]
Hi,

I am using bootstrap 2.3.2 and jQuery version 1.10.2. Tagging is working great but if I used along with typeahead then I got below error message in bootstrap-typeahead.js (V1.2.2). If I try typeahead alone without tags then typeahead is working great. Please help me out to solve this issue.

<input type="text" class="span12" id="inputTo" value="Amsterdam,Washington" data-role="tagsinput" />

$('#inputTo').tagsinput({
  typeahead: {
    source: ['Amsterdam', 'Washington', 'Sydney', 'Beijing', 'Cairo']
  }
});

Error:
TypeError: data[0] is undefined
http://localhost/app/plugins/typeahead/bootstrap-typeahead.js
Line 240

Regards,
Thileepan S.

**Comment by mchateloin** [comment]
Same issue here. Bootstrap 3.3.1. Options I'm setting are:
```
{
                trimValue: true,
				maxTags: 10,
                typeahead: {
                    source: ['mick', 'casdf','asdf']
                },
                itemValue: 'text',
                freeInput: true
}
```
