### ISSUE TITLE
Does not seem to work with iron:router

### ISSUE THREAD

**Issue by mcrisp** [bootstrap-tagsinput/bootstrap-tagsinput#270]
When I add the following code within a normal html page within meteor, it works fine.
<input type="text" value="Amsterdam,Washington,Sydney,Beijing,Cairo" data-role="tagsinput" />

However, when I add that same code within a page served by iron:router I just get a text field with "Amsterdam,Washington,Sydney,Beijing,Cairo" in the text field.  No formatting is done to look like tags.

here is a link to a screen shot of the sample output.  You can see the code within the iron:router page does not get transformed correctly. 

https://drive.google.com/a/power-story.com/file/d/0B5iYquzTGAWLYUF4UGo0OUlfVWs/view?usp=sharing

**Comment by zleman1593** [comment]
Try running this when the {{>yield}} is rendered/created: 

```
 $("input[data-role=tagsinput], select[multiple][data-role=tagsinput]").tagsinput();
```

Currently the script runs once per page load, and not again once IR renders the new template. You need to make it run again by using the above code. Let me know if this soves your issue.
