### ISSUE TITLE
Not deny case insensitive duplicate tag?

### ISSUE THREAD

**Issue by adilsonb** [bootstrap-tagsinput/bootstrap-tagsinput#276]
The scripts deny only case sensitive duplicate tags...

In sample page if I add a tag "cairo" it´s accepted...

Any way to add a option to choose the case of duplicate tag?

Thanks!

**Comment by nhouse** [comment]
I added this as an option and made pull request https://github.com/timschlechter/bootstrap-tagsinput/pull/328

In the meantime, or if Tim rejects it, you can look at the pull request to see the changes I made. You can also hardcode this behavior by changing line 104:

    var existing = $.grep(self.itemsArray, function(item) { return self.options.itemValue(item) === itemValue; } )[0];

To:

    var existing = $.grep(self.itemsArray, function(item) { return self.options.itemValue(item).toLowerCase() === itemValue.toLowerCase(); } )[0];

**Comment by leonardonsantos** [comment]
I handled this issue transforming everything to lower case before insert tag:

```javascript
$(input).on('beforeItemAdd', function(event) {
    if (event.item !== event.item.toLowerCase()) {
        event.cancel = true;
        $(this).tagsinput('add', event.item.toLowerCase());
    }
});

```

**Comment by ahmedaziz63** [comment]
This worked for me in active admin form

$(function () {
  $(document).on('beforeItemAdd', 'input', function(event) {
      if (event.item !== event.item.toLowerCase()) {
          event.cancel = true;
          $(this).tagsinput('add', event.item.toLowerCase());
      }
  });
});

**Comment by ahmedaziz63** [comment]
It  worked for me in active admin form same as above

`$(function () {
  $(document).on('beforeItemAdd', 'input', function(event) {
      if (event.item !== event.item.toLowerCase()) {
          event.cancel = true;
          $(this).tagsinput('add', event.item.toLowerCase());
      }
  });
});`

**Comment by ahmedaziz63** [comment]
It worked for me in active admin form in rails, same as above

$(function () {
  $(document).on('beforeItemAdd', 'input', function(event) {
      if (event.item !== event.item.toLowerCase()) {
          event.cancel = true;
          $(this).tagsinput('add', event.item.toLowerCase());
      }
  });
});
