### ISSUE TITLE
tagsinput does not process the return value of source: parameter

### ISSUE THREAD

**Issue by AlexCppns** [bootstrap-tagsinput/bootstrap-tagsinput#284]
I have the following:

```
$('.url-filter').tagsinput({ typeahead: {
    source: function (query) {

      console.log(query);
      return $.ajax({
        url:'/campaigns/url_filters',
        data: { query: query },
        success: function (data) {
          return data.options;
        }
      });
    }
 }});
```

which is not parsed properly because the object returned to tagsinput seems to be data and not data.options.

**Comment by lucknerjb** [comment]
You'll want to name the options parameter "typeaheadjs" and not "typeahead". Give that a shot and let me know if you're still having issues
