### ISSUE TITLE
Edit exiting tags

### ISSUE THREAD

**Issue by pravin-d** [bootstrap-tagsinput/bootstrap-tagsinput#286]
Is it possible to edit the existing tags ?

**Comment by lucknerjb** [comment]
You can't edit an existing tag but you are able to move the cursor in the field to be at the tag position that you need, remove the tag, type in a new value and create a tag from this new value.

**Comment by agladysh** [comment]
I would also like to be able to edit existing tags. I like how https://github.com/bevacqua/insignia/ handles the user experience on this matter. 

Any input on how to achieve this with the tagsinput?

**Comment by pravin-d** [comment]
@lucknerjb
Okay.. thank you

**Comment by agladysh** [comment]
...For starters I tried to implement removal on doubleclick:

```javascript
$(".bootstrap-tagsinput").on("dblclick", ".tag", function(e) {
    $(this).parent().tagsinput('remove', $(e.target).data('item'));
  })
  ;
```

But it acts really weird, including resetting tagsinput options. What am I doing wrong?

**Comment by agladysh** [comment]
Regarding weird behaviour: see #306.

**Comment by lucknerjb** [comment]
@agladysh I like how they handled the editing of the tags. I'll have a look at that this weekend. It would be a nice option to have for sure.

**Comment by aravind2base** [comment]
Any update on this issue?
Can we implement something like this https://bevacqua.github.io/insignia/
Its kind of works like the same as tags input but also have the edit operation
