### ISSUE TITLE
Use tab key in confirmKeys option

### ISSUE THREAD

**Issue by Blinkers** [bootstrap-tagsinput/bootstrap-tagsinput#302]
Hi,

For using the tab key in option "confirmKeys" we need to modifiy this : 
line 591
`if (typeof (keyCombination) === 'number' && keyPressEvent.which === keyCombination) {`
to this
`if (typeof (keyCombination) === 'number' && (keyPressEvent.which === keyCombination || keyPressEvent.keyCode === keyCombination)) {`

But if you presse tab key keyPressEvent.which == 0, you need to check the keyCode.

**Comment by agladysh** [comment]
+1

**Comment by GarageWeb** [comment]
+1
