### ISSUE TITLE
Improve documentation for typeahead.js support

### ISSUE THREAD

**Issue by agladysh** [bootstrap-tagsinput/bootstrap-tagsinput#305]
It seems that only Bootstrap 2 typeahead is supported at this moment. Please support typeahead.js, that is recommended for Bootstrap 3:

http://twitter.github.io/typeahead.js/

**Comment by pitaj** [comment]
It is supported. I haven't been able to get it to work, though.

**Comment by agladysh** [comment]
Well, I stopped my research at not being able to pass the datasets to the typeahead object (and upon seeing typeahead version 2.3.2 in the sources).

I'm not sure how this will work with standalone bootstrap.js:

https://github.com/TimSchlechter/bootstrap-tagsinput/blob/master/src/bootstrap-tagsinput.js#L270

**Comment by pitaj** [comment]
https://github.com/TimSchlechter/bootstrap-tagsinput/blob/master/src/bootstrap-tagsinput.js#L321

It shows it working with typeahead.js in the examples.

**Comment by agladysh** [comment]
Ah, now I see: `typeahead` vs. `typeaheadJS`. Sorry for the noise then. Will try to make it work.

**Comment by pitaj** [comment]
Alright, so you can't have the `data-role` attribute and then afterwards apply the typeaheadjs stuff for some reason. That was my issue.

**Comment by agladysh** [comment]
I probably am missing something, but how do I pass multiple datasets and typeahead.js options to the typeahead object?

Compare to how the tokenfield does the typeahead initialization: https://github.com/sliptree/bootstrap-tokenfield/blob/master/js/bootstrap-tokenfield.js#L194

**Comment by pitaj** [comment]
To pass multiple datasets, include the objects in an array, and pass the array, like so:

```
[
  {
    name: "one",
    ...
    source: one.ttAdapter()
  },
  {
    name: "two",
    ...
    source: two.ttAdapter()
  }
]
```

**Comment by agladysh** [comment]
Ok, thanks! And how to pass the typeahead options?

**Comment by pitaj** [comment]
You can't, sadly. You would have to modify the code.

**Comment by agladysh** [comment]
I can, I think, by working directly with the `tagsinput('input')` object.

BTW, `typeaheadjs` option is not documented despite being used in an example. It probably should be (and older `typeahead` option probably should be marked as deprecated).

**Comment by lucknerjb** [comment]
Hey guys, I'll be working on allowing typeahead options tomorrow evening. It might take a few iterations but I think we'll be able to solidify typeahead integration.

**Comment by tbrammar** [comment]
@lucknerjb did you manage to get the typeahead integration more solidified?

**Comment by vceron** [comment]
@lucknerjb as addition to @tbrammar question, did you manage to add typeahead options?

**Comment by jcrben** [comment]
I found that twitter typeaheadjs basically works with some quirks. Note that the twitter typeaheadjs library is abandoned (see https://github.com/twitter/typeahead.js/issues/1320); there is an active fork starting at https://github.com/corejavascript/typeahead.js
