### ISSUE TITLE
Remove button is broken with allowDuplicates

### ISSUE THREAD

**Issue by agladysh** [bootstrap-tagsinput/bootstrap-tagsinput#306]
Steps to reproduce:

``` javascript
$(".input")
  .tagsinput({
    allowDuplicates: true
  })
  ;
```
1. Add two tags with value `123`.
2. Click `x` button on either of tags.

Bug: Both tags are removed (seems that only from the DOM, though).
Expected: A single tag is removed, precisely the one whose removal button was clicked.

**Comment by alejandrosack** [comment]
I have the same problem.
