### ISSUE TITLE
if input typed tags > maxTags dropdown still showing

### ISSUE THREAD

**Issue by hitodev** [bootstrap-tagsinput/bootstrap-tagsinput#307]
Hello

If typed tags exceeds maxTags value, the limitation works fine but input still presenting the dropdown with possible value, is there a way :

- to prevent (hide) dropdown/value suggestions when user try to enter maxTags  + 1
- or to show a message when user try to enter maxTags  + 1 (e.g. : "max allowed inputs for this field : maxTags") ?

(bootstrap 3 version)

**Comment by hitodev** [comment]
temp. fixed by adding 

.bootstrap-tagsinput-max .tt-input{display:none;}

**Comment by lucknerjb** [comment]
This is definitely a valid point but I'm not sure how to attack it exactly. Showing an error message to the user is not an option as there are too many UI / UX considerations to take into account and it's outside of the scope of the plugin.

As for not showing the dropdown... I think that should be left to the developer.

Maybe something like:

- user enters 5 tags. 5 is the max they are allowed
- on the 5th tag, the "maxItemsReached" event is fired
- the developer runs code such as this:
```
$('.bootstrap-tagsinput-max .tt-input').css('display', 'none');
```
- if the user removes a tag, the "itemRemoved" event is fired (as is the case now) and the dev can now remove his custom CSS

I think adding this extra event is the way to go to keep the plugin's footprint / scope as small as possible

**Comment by lucknerjb** [comment]
I've thought about this some more and I don't think adding another event is the way to go. Does this event only get fired when the max was reached? Should it be fired if the user continues to try and add a tag? I think that there are too many different use cases.

Easiest solution:
* Initiate a counter on your end
* Increment the counter by hooking into the itemAdded event
* Handle the max items reached event yourself

Closing ticket as this feature will not be added.
