### ISSUE TITLE
Add minLength support using typeahead

### ISSUE THREAD

**Issue by ericlin382002** [bootstrap-tagsinput/bootstrap-tagsinput#314]
Is there any way to use minLength in typeahead which minimum character length needed before suggestions start getting rendered?

**Comment by lucknerjb** [comment]
There isn't an option to pass the main config to typeahead but this is something that should be done. I'll whip up a commit tomorrow evening and get that pushed to master

**Comment by gdibble** [comment]
@ericlin382002 done
@lucknerjb no intention to step on your toes - i needed this feature in production today to i forked to [my-own](https://github.com/gdibble/bootstrap-tagsinput) and fixed it for everyone ;)
@timschlechter please review PR #319

**Comment by lucknerjb** [comment]
@gdibble No worries man, I actually finished coding this last night but didn't have time to push it to master. I'll merge some of your changes with mine and update your PR here and merge it in with master.

Thanks for putting in the work mate!

**Comment by gdibble** [comment]
:+1: anytime :) always happy to help

**Comment by JesseWynants** [comment]
I was wondering if this is going to be merged in? Seems like a logical enhancement.

**Comment by lucknerjb** [comment]
This was added here: 431deec76b0a9a54db1323c61925d35abc49ffec

Basically, you pass an array as the "typeaheadjs" config option. The first object in the array are your typeahead options - where you would put minLength - and the second one is the data set options.

Ex:

```
$(element).tagsinput({
  typeaheadjs: [
      {
         minLength: 4
      },
      {
       name: 'citynames',
       displayKey: 'name',
       valueKey: 'name',
       source: citynames.ttAdapter()
     }
  ]
});
```

**Comment by lucknerjb** [comment]
I should add that in a future version, we'll be modifying the API to take in an object with the keys "options"  and "datasets", as proposed by the above PR. Much cleaner than the array of objects that we have at the moment.

**Comment by popovae** [comment]
Not working with 0 value in  minLength...any suggestions?
