### ISSUE TITLE
insert between existing tags with mouse click

### ISSUE THREAD

**Issue by sowirepo** [bootstrap-tagsinput/bootstrap-tagsinput#321]
It is already possible to insert tags between existing tags using the cursor, but it would be nice if it was also possible to position the cursor on a mouse click between existing tags.

**Comment by tomazov** [comment]
use
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<script type="text/javascript">
$(document).ready(function () {
     $('#name').tagsinput({
            tagClass: 'label label-default label-slow',
            trimValue: true,
            allowDuplicates: true,
            freeInput: true
        });
    $('.bootstrap-tagsinput').sortable();
});
</script>
