### ISSUE TITLE
Sugestion to make dinamic

### ISSUE THREAD

**Issue by opvini** [bootstrap-tagsinput/bootstrap-tagsinput#323]
Hi everyone.
I was testing and I modified the JS file on

"width: "+d+" !important;" // ON LINE 47 OF bootstrap-tagsinput.js
to
"max-width: 100% !important; width: auto !important;"

making the field more dinamic.
Thereby we can write to the end of the field, and we can specify the width of field.

Sorry my english, i am from Brazil.
Thanks a lot!

**Comment by nhouse** [comment]
Amazing timing. I was just messing around with the code myself to try to accomplish this and my solution was to make everything float left. I just did this in chrome dev tools and didn't actually modify the source, but it would work.

Your solution seems more elegant, but it has one problem: text overflows the input. Here's a screenshot showing this:

![clipboard image 31](https://cloud.githubusercontent.com/assets/2923538/6763812/41a09fc2-cf65-11e4-86e1-70eef42f567d.png)

So with your solution, there needs to be a way to limit the width to the width of the input (if it's fixed width).

**Comment by nhouse** [comment]
I think this works:

    this.$input.get(0).style.cssText = "max-width: " + this.$element.width() + "px !important; width: auto !important;";

This only fixes the above problem if the input is fixed width (such as in pixels). If the input TagsInput is being added to has a width set in percent, the above problem still exists.

P.S. if you add four spaces before your code, it gets formatted like the above.

**Comment by opvini** [comment]
Cool!!
But I modified the style too, sorry for didn't mencioned:

.bootstrap-tagsinput {	
  position: relative;
  display: inline-block;
  color: rgba(0, 0, 0, 0.8);
  cursor: text; 
  margin: 0em;
  width: 100% !important;
  max-width: inherit;
  outline: none;
  -webkit-tap-highlight-color: rgba(255, 255, 255, 0);
  text-align: left;
  line-height: 1.2142em;
  font-family: 'Lato', 'Helvetica Neue', Arial, Helvetica, sans-serif;
  padding: 0.67861em 1em;
  background: #ffffff;
  border: 1px solid rgba(0, 0, 0, 0.15);
  color: rgba(0, 0, 0, 0.8);
  border-radius: 0.2857rem;
  -webkit-transition: background-color 0.2s ease, box-shadow 0.2s ease, border-color 0.2s ease;
  transition: background-color 0.2s ease, box-shadow 0.2s ease, border-color 0.2s ease;
  box-shadow: none;
}


.bootstrap-tagsinput input {
  border: none !important;
  box-shadow: none !important;
  outline: none !important;
  background-color: transparent !important;
  padding: 0 !important;
  margin: 0 !important;
  width: 100% !important;
  max-width: inherit !important;
}

**Comment by nhouse** [comment]
That CSS didn't work for me unfortunately, and the "fix" I posted doesn't work well because the input width defaults to the width of it's parent, which results in a second row being added to the container. It would be great if an official patch could be made to the plugin.

**Comment by nhouse** [comment]
That CSS didn't work for me unfortunately, and the "fix" I posted doesn't work well because the input width defaults to the width of it's parent, which results in a second row being added to the container. It would be great if an official patch could be made to the plugin.

@timschlechter what do you think? The issue we're trying to fix is that when you add a long tag, such as `this is a really long tag`, the input width remains fixed and the text gets cut off:

![image](https://cloud.githubusercontent.com/assets/2923538/6852373/ae5b70ac-d3ba-11e4-835b-0cab74e1f2bb.png)

Once enter is pressed, then it displays nicely:

![image](https://cloud.githubusercontent.com/assets/2923538/6852385/baf001a2-d3ba-11e4-8bd8-4b19bbbc0643.png)

**Comment by opvini** [comment]
@nhouse do you try use my CSS and my modification on js?
For me it works fine...

![tagsinput](https://cloud.githubusercontent.com/assets/7398397/6870158/e994de24-d478-11e4-8d7b-414544f0c785.jpg)

**Comment by opvini** [comment]
And I fixed the width:

.mytagsinput{
	width: 200px !important;
}
