### ISSUE TITLE
TypeError: self.options.itemValue(...) is undefined

### ISSUE THREAD

**Issue by yoyhosoft** [bootstrap-tagsinput/bootstrap-tagsinput#324]
I use jQuery Version 2.1.3

When I add item via below code:
    elt.tagsinput('add', { "value": 1 , "text": "Amsterdam"   , "continent": "Europe"    });
It's error with: 
    TypeError: self.options.itemValue(...) is undefined
    return self.options.itemValue(item).toString();
    bootstr...nput.js (line 244)

**Comment by rzds** [comment]
Maybe it helps someone. I had this error in BS 2.3.2 when clicking on suggestions instead on pressing enter. I've added that *if* and the error is gone.


```js
   pushVal: function() {
      var self = this,
          val = $.map(self.items(), function(item) {
              //add this condition
              if(typeof self.options.itemValue(item) !== 'undefined'){ 
                    return self.options.itemValue(item).toString();
              }
          });

      self.$element.val(val, true).trigger('change');
    }
