### ISSUE TITLE
Greedy backspace

### ISSUE THREAD

**Issue by vba** [bootstrap-tagsinput/bootstrap-tagsinput#329]
Greetings,

I've noticed strange behaviour of tagsinput, more exactly it deletes more that you could expect. When your have for example at least one tag and few text right below, if you select this text and press backspace key(only once), tagsinput will remove selected text and also previous tag.

![greedy_backspace](https://cloud.githubusercontent.com/assets/420881/6917978/09cd39e6-d7aa-11e4-9cd5-388b702e9a63.gif)

Normally you could expect that it will delete only select text.

Many thanks.

**Comment by tgxworld** [comment]
:+1: I'm seeing this too.

**Comment by samholmes** [comment]
This is related to an issue I just posted: https://github.com/timschlechter/bootstrap-tagsinput/issues/367

Not only is this a problem, but the delete key is also handled incorrectly. The solution for this problem is to check if there is a selection before checking the caret position.

**Comment by tim-peterson** [comment]
Issue is resolved by #450. 

Here's what I added to the library:

```
          case 8:
            if (doGetCaretPosition($input[0]) === 0) {
              var prev = $inputWrapper.prev();
              if (prev.length) {
                var prev_item = prev.data('item');
                // <<<<< TRP 12/27/15
                if((typeof prev_item === 'string' && prev_item ==$input.val()) || (typeof prev_item === 'object' && prev_item.name == $input.val())){
                  //console.log('remove b/c same name=value');
                  self.remove(prev.data('item'));
                }
                else{
                  //console.log('DONT remove b/c NOT sames name=value');
                }
                // >>>> TRP 12/27/15

              }
            }
            break;
```

**Comment by rtselva03** [comment]
thank you buddy its working fine...................:)

**Comment by benediktscherer** [comment]
For me it does not work either …

**Comment by roddydairion** [comment]
Has anybody been able to solve this issue?

**Comment by roddydairion** [comment]
@tim-peterson thank you. You changes work. I was calling the min.js file, instead of the normal .js file for bootstrap tagsinput.
