### ISSUE TITLE
No css for dropdown menu with typeahead

### ISSUE THREAD

**Issue by Blackvz** [bootstrap-tagsinput/bootstrap-tagsinput#342]
Hey I am using your plugin and I also used typeahead with it.
But my suggestions are just shown in a dark color and theres no style on it.
I included everything

link href="../library/bootstrap/css/bootstrap.min.css" rel="stylesheet">
link href="../library/bootstrap/css/bootstrap-theme.css" rel="stylesheet">
link rel="stylesheet" type="text/css" href="css/bootstrap-tags/bootstrap-tagsinput.css"/>
script src='js/bootstrap-tags/bootstrap-tagsinput.js'></script>
script src='js/bootstrap-tags/bootstrap-tagsinput-angular.min.js'></script>

Thats how i use it :

div class="container">
        input type="text" value="Allgemeines" data-role="tagsinput" name="formdata[tags]" class="bootstrap-tagsinput">
 /div>

I tried everything..also included your app.css of your github page..Still dont work..
Hope you can help me :S

**Comment by alexbooker** [comment]
I am experiencing something similar..

**Comment by alexbooker** [comment]
Solution: https://github.com/timschlechter/bootstrap-tagsinput/issues/345
