### ISSUE TITLE
 beforeItemRemove function?

### ISSUE THREAD

**Issue by michaelDotco2** [bootstrap-tagsinput/bootstrap-tagsinput#350]
When you press the delete key when you are in the input, the tag gets deleted.

Is there some way / function to initialize a warning / modal / confirmation?

This would prevent accidents from happening.

**Comment by lucknerjb** [comment]
There is an beforeItemRemove function:

http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/

**Comment by biswajit-paul** [comment]
This works on browser confirm action but how does it work on sweetalert2? I tried with async/await but somehow it failed.
