### ISSUE TITLE
Removing items when allowDuplicates is true

### ISSUE THREAD

**Issue by n0nick** [bootstrap-tagsinput/bootstrap-tagsinput#351]
When using the `allowDuplicates: true` option, item removal is buggy -- removing one item causes:

1._All_ tag DOM elements to be removed (because you're searching for it using `$.filter`).
2. Only one item is removed from the input's value - always _the first one_, regardless of the item that was removed (because you're using `$.inArray`).

See this link for a test case: http://jsfiddle.net/9nouy156/

I'll submit a pull request with unit tests and a suggested fix in a few minutes.

**Comment by gigatyrant** [comment]
Is it possible to integrate this correction to the Master ?

**Comment by n0nick** [comment]
Would be awesome :) Do you need me to rebase my change?

**Comment by palerdot** [comment]
1.5 years on this is still a painful issue to deal with. The demo fiddle is not working. Following is a working fiddle of this bug.

https://jsfiddle.net/g1qxn1yz/2/

Right now, there is all sorts of hacks needs to be done, like `removeAll` all the entries when removed, then compare the internal `items` array and add them one by one. There are some painful side effects to this like the `add` Event is triggered for each item, but this is the closest I can do to deal with this issue.
