### ISSUE TITLE
Force everything to lowercase/uppercase

### ISSUE THREAD

**Issue by FoxDanger** [bootstrap-tagsinput/bootstrap-tagsinput#354]
There's a way to force all items be lower/upper case?

If not, can be implemented?

Or maybe there's a way to don't permit equal inputs like:

[Home, home]

**Comment by kcheco** [comment]
hi FoxDanger,

if you are loading up the raw js version of boostrap-tagsinput then add a uppercase option at the top where it says defaultOptions.

uppercase: function(item) {
      return item ? item.toUpperCase() : item;
    }

You can also do the same if you want to force the api to always capitalize the first letter

capitalize: function(item) {
      return item ? item.charAt(0).toUpperCase() + item.slice(1) : item;
    }

This method would only allow you set one of the options above to avoid errors.

**Comment by FoxDanger** [comment]
Tnx kcheco!

I can do something like this too?

$("#referenciasAulasInput").typeahead({
             uppercase: function(item) {
                 return item ? item.toUpperCase() : item;
             },
            updater: function(item) {
                objetoReferenciaAula = {
					numero: item.id_aula,
					titulo: item.titulo,
					classe: item.classe,
					disciplina: item.disciplina
				};
                return item;
            },
 			source: arrayAulasInterativas,
        });

**Comment by jhilden** [comment]
this helped me https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/276#issuecomment-231095953

**Comment by rayhannr** [comment]
in this case, I want my tag input to be capitalized each word. So, in the raw taginputs.js, add a key for example "titleCase" having a function as its value inside the defaultOptions object. Then assign it in the "itemValue" key. Here's the code

var defaultOptions = {
      titleCase: function(str) {
        var splitStr = str.toLowerCase().split(' ');
        for (var i = 0; i < splitStr.length; i++) {
            splitStr[i] = splitStr[i].charAt(0).toUpperCase() + splitStr[i].substring(1);     
        }
        return splitStr.join(' '); 
     },
itemValue: function(item) {
        return  this.titleCase(item);
      },
