### ISSUE TITLE
beforeItemAdd never call and not possible to add new item

### ISSUE THREAD

**Issue by a3code** [bootstrap-tagsinput/bootstrap-tagsinput#356]
I have next code 
`var categoriesList = new Bloodhound({
                    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
                    queryTokenizer: Bloodhound.tokenizers.whitespace,
                    prefetch: {
                        url: '/api/BrandsService/GetCategories',
                        filter: function(list) {
                            return $.map(list, function(cname) {
                                return { name: cname }; });
                        }
                    }
                });
                categoriesList.initialize();

                var elt = $('#categoriesList');
                elt.tagsinput({                  
                    tagClass: 'label label-primary',
                    freeInput:false, 
                    confirmKeys: [13, 32, 44],
                    trimValue: true,
                    itemValue: 'id',
                    itemText: 'name',                  
                    typeahead: {
                        name: 'categoriesList',
                        displayKey: 'name',                        
                        source: categoriesList.ttAdapter()
                    }
                });
         
                for (var i = 0; i < self.jsonData.categories.length; i++) {
                    elt.tagsinput('add', self.jsonData.categories[i]);
                }`

it is working only for show and delete some object, I try to type new value but it never added to list

my control is inside form, and enter click call submit form.

I tried to use beforeItemAdd but it never calls as well
`
 $('#categoriesList').on('beforeItemAdd', function(event) {          
            event.item = {id:-11,name:event.item};            
            // event.item: contains the item
            // event.cancel: set to true to prevent the item getting added
        });
`

beforeItemRemove working good
 
more over typeahead not working as well by some reason...

an

I am using latest bootstrap 3.4,
How I can solve it ?

**Comment by lucknerjb** [comment]
This is quite an old issue and the event fires as it should so I'll close the issue for now. Please let me know if you're still having trouble with this.
