### ISSUE TITLE
NPM version update issue

### ISSUE THREAD

**Issue by lucknerjb** [bootstrap-tagsinput/bootstrap-tagsinput#357]
Creating this ticket to keep track of a comment on #338. There seems to be a small problem with the NPM package at the moment. I'm currently trying to resolve this and will post an update here once the issue is resolved. Note, this may take a couple to a few weeks.

**Comment by lucknerjb** [comment]
I should clarify, the reason this may take a couple to a few weeks is that I've had to involve NPM support. I'll post an update as soon as I have one!

**Comment by milotoor** [comment]
Thanks @lucknerjb!

**Comment by lucknerjb** [comment]
Still haven't heard back so I'll give it a few more days and check in with NPM at the end of the weekend

**Comment by milotoor** [comment]
Thanks again for following up with this

**Comment by Ardakilic** [comment]
Hello, is #366 related to this?

**Comment by milotoor** [comment]
I can't say definitively, but my guess is no. This issue was originally raised because the NPM package was out of date: v. 0.4.2 is what is available, but 0.5.0 is the latest. The issue here is just publishing 0.5.0. However, that has evidently been troublesome, and I suppose it's possible that there could be an interim problem installing as the NPM issue is resolved. @lucknerjb will have to respond to give you a proper answer...

**Comment by milotoor** [comment]
I should also mention that I am not having any issues with installing via NPM.

**Comment by Ardakilic** [comment]
@milotoor Thank you for the answer. What's your exact setting for this plugin in package.json file currently?

This was available a while ago: https://www.npmjs.com/package/bootstrap-tagsinput

Also there is no search result: https://www.npmjs.com/search?q=bootstrap-tagsinput

**Comment by lucknerjb** [comment]
@milotoor & @Ardakilic We actually just got a response from npm about 10 hours ago. The issue with the package is resolved and we're free to re-publish it to npm, which I will do tonight once I get home.

The only issue is that we won't be able to use previous versions of the plugin via npm. So if someone was using or wanted to use v 0.3.0, they would have to manually download it from Github and extract it into their project. Aside from that, the current (0.5.0) and future versions will all be available.

I believe #366  will be fixed by re-publishing the package as well

**Comment by milotoor** [comment]
Excellent! Thanks a bunch @lucknerjb!!

**Comment by Ardakilic** [comment]
Great news @lucknerjb , thanks for the heads-up!

**Comment by lucknerjb** [comment]
And here we go guys: https://www.npmjs.com/package/bootstrap-tagsinput

**Comment by milotoor** [comment]
Thanks again :)

**Comment by Ardakilic** [comment]
Thank you, sorry for the late reply, I can confirm it work as a treat!

**Comment by maxtheaviator** [comment]
Hey, would it be possible to update the npm to current v 0.8.0 
Would be amazing ;) Thx a lot!
