### ISSUE TITLE
Planning transfer of ownership of the repository

### ISSUE THREAD

**Issue by timschlechter** [bootstrap-tagsinput/bootstrap-tagsinput#363]
Hello!

As some might have noticed... I haven't been actively maintaining this project for some (long, long...) time now. Since I started this project, it got a lot more traction than I anticipated. Because of my work and other projects I'm working on, I can't seem to make the time and effort in this project it deserves.

Fortunately, @lucknerjb is willing to take over the project!

Are there any problems to expect when [transferring the repository](https://help.github.com/articles/transferring-a-repository/)? If I understand correct, most things should keep working as normal. Links, github pages, issues, open pull request: all should be transfered/redirected automatically

The only inconvenience I can see is that that users who have forked your repository will need to update their remote URLs to point to the new Git repository in order to continue opening pull requests.

Are there any other problems to expect?

**Comment by methodbox** [comment]
Well right now you have at least 3 variations that exist @ Atmospherejs.org. So you might want to first correct those links to actually go to the correct repo.

I've installed 2 non-functional versions in Meteor so far.  I'll try this one next.

**Comment by KrunchMuffin** [comment]
what is the status of this project and the transfer? I would like to implement this plugin, but will it be maintained?

**Comment by lucknerjb** [comment]
Hey Derek,

This project will be maintained. I've literally been handcuffed day and
night by this huge project at work for the better part of the last 6-8
weeks but we're back to business as usual. This coming week, I'll be taking
inventory of where things are at with the plugin and getting back to issues
/ PRs.

_____________

Luckner Jr.
Twitter: @lucknerjb
Co-Founder, ShowkasePad | Going Beyond the Resume
http://showkasepad.com
<info@tekcastdesigns.ca>

**Comment by KrunchMuffin** [comment]
Thanks for letting me know. I am already having an issue which I have
posted.

**Comment by jcrben** [comment]
The associated twitter typeaheadjs library is similarly unmaintained (see https://github.com/twitter/typeahead.js/issues/1320).

A group have started a fork over at https://github.com/corejavascript/typeahead.js

I would recommend that you move this repository to an organization and that seems like a reasonable one. At the very least, we need to make sure there's communication between the two groups.

**Comment by lucknerjb** [comment]
@jcrben Thanks for the info re the CoreJavascript group. I'll be updating the plugin to use their fork instead of twitter's version and will keep an eye out on them for updates.
