### ISSUE TITLE
dist/bootstrap-tagsinput.min.js.map is wrong

### ISSUE THREAD

**Issue by hugopeixoto** [bootstrap-tagsinput/bootstrap-tagsinput#371]
The contents of `dist/bootstrap-tagsinput.min.js.map` seem to have been ill-generated.
Its contents seem to be for the `dist/bootstrap-tagsinput-angular.min.js` file:

    {
      "version":3,
      "file":"dist/bootstrap-tagsinput-angular.min.js",
      "sources":["src/bootstrap-tagsinput-angular.js"],
      ...

I think this happens because `Gruntfile` has the following options in the uglify section, which causes it to always write the source map to the same file, independently of the original filename:

    sourceMap: 'dist/<%= pkg.name %>.min.js.map',
    sourceMappingURL: '<%= pkg.name %>.min.js.map'

I updated `grunt-contrib-uglify` from version 0.2.2 to 0.9.1 and ran `grunt build`. The source maps looked OK after this change.

    npm install grunt-contrib-uglify@0.9.1 --save-dev
    grunt build

I would create a PR for this but I can't seem to get the tests to run locally. I'll see if I can figure it out.

**Comment by lucknerjb** [comment]
Thanks a lot for pointing that out. Will get it fixed ASAP. Any luck getting the tests working on your end? Not sure if I can help any but let me know if I can.

**Comment by hugopeixoto** [comment]
I managed to get the tests running a while ago, but forgot to make the PR.
I was using my forked version with the fix and it seemed to work without problems as well.
