### ISSUE TITLE
the width of input text not dynamic with inputSize

### ISSUE THREAD

**Issue by tuanhai12h** [bootstrap-tagsinput/bootstrap-tagsinput#372]
sorry, I wrong the old version, when I check newest version not happens.

In the file, have !important code made demo wrong.
http://timschlechter.github.io/bootstrap-tagsinput/examples/lib/bootstrap-tagsinput/bootstrap-tagsinput.js

Thanks,

**Comment by lucknerjb** [comment]
Just want to make sure I understood you properly. You added some CSS to make the tagsinput box the same length as your own input but it did not work?

Can you provide your HTML and CSS snippets in a jsfiddle?
