### ISSUE TITLE
onblur not working for typeahead

### ISSUE THREAD

**Issue by stephenlawrence** [bootstrap-tagsinput/bootstrap-tagsinput#378]
If I use the typeahead example, enter an unknown value then click off the input box I would expect the value to be added similar to the non-typeahead example.

**Comment by lucknerjb** [comment]
Not quite as with autocompletes, one expects a user to manually select the option that is appropriate.

**Comment by stephenlawrence** [comment]
My specific use case is using it on a "Tags" type input field. When someone enters an unknown tag and clicks into the next field w/o Enter/Tab, the tag field does not trigger properly so it never gets registered as a tag and does not get saved.

**Comment by joekeen** [comment]
Also, if you use the typeahead example, enter an unknown value and hit enter to create the tag, then tab off the input box - the just typed tag name appears twice.

![screen-shot-2015-08-19-at-83627-pmpng](https://cloud.githubusercontent.com/assets/1745655/9354267/630e7994-46b2-11e5-8a44-f0aed1d0be04.png)

**Comment by lucknerjb** [comment]
@stephenlawrence I know this issue is kind of old but maybe handling adding the content of the input as a tag manually by registering an onblur event for your input would be a possibility?

If this is no longer an issue, please close the ticket :-)
