### ISSUE TITLE
Don't show entered tags in typeahead when allowDuplicates is false

### ISSUE THREAD

**Issue by xplicit** [bootstrap-tagsinput/bootstrap-tagsinput#381]
This is an enhancement request. When I use tagsinput with `allowDuplicates: false`, typeahead shows  all tags values which are contained in data source. But in most cases it's not necessary to show the tags, which already were entered in the tagsinput control. It would be better if tagsinput filters out these values and does not show them at all, because user can not add them anyway.

**Comment by lucknerjb** [comment]
There's some investigation to be done here. I'm not sure whether or not this is possible... think about a scenario where the typeahead source returns hundreds of items. Not a big datasource by any means but having to match entered tags with that source and remove them... not sure if that's the only / best way of handling this scenario.

I'll leave the issue open for now and see if it gains any traction.
