### ISSUE TITLE
All jQuery versions supported ?

### ISSUE THREAD

**Issue by mrhmansour** [bootstrap-tagsinput/bootstrap-tagsinput#382]
it's not work with jQuery 2.0.2 !!

**Comment by lucknerjb** [comment]
I'll have a look at what might not be working with the newer version of jquery but in the meantime, can you post what hasn't worked for you so far? Any error messages in the console?

**Comment by lucknerjb** [comment]
@mrhmansour Updated to 2.1.4 without any issues. Let me know if you're still having issues. Closing for now.
