### ISSUE TITLE
Typeahead and free input

### ISSUE THREAD

**Issue by Stnaire** [bootstrap-tagsinput/bootstrap-tagsinput#387]
Free input option doesn't work when combined with typeaheadjs.
The problem seems to come from bootstrap-tagsinput.js line 354 : 

``` javascript
// HACK: only process on focusout when no typeahead opened, to
//       avoid adding the typeahead text as tag
if ($('.typeahead, .twitter-typeahead', self.$container).length === 0) {
    self.add(self.$input.val());
    self.$input.val('');
}
```

The condition used to detect if there is an active suggestion is buggy, the following condition seems to work as excepted : 

``` javascript
if ($('.tt-hint', self.$container).val().length === 0) {
    self.add(self.$input.val());
    self.$input.val('');
}
```

But here comes an another problem, the input field is not cleared after the value is added as tag.
Typeahead's onblur event is trigger after the input is cleared, and because it's internal value hasn't changed, it sets back the input with it.

The correct code could be : 

``` javascript
if ($('.tt-hint', self.$container).val().length === 0) {
    self.add(self.$input.val());
    self.$input.typeahead('val', '');
    self.$input.typeahead('close'); 
}
```

Regards.

**Comment by joekeen** [comment]
See also Issue [386](https://github.com/timschlechter/bootstrap-tagsinput/issues/386).

**Comment by Mbertu** [comment]
This fix works, but if you wrap it in the if clause, when you insert a string that is a piece of typeahead suggestion you have the same original problem.

Why the:
```javascript
if ($('.tt-hint', self.$container).val().length === 0) {
...
```

**Comment by lucknerjb** [comment]
This should have gone out in 0.8.0 but moving it down to 0.9.0 for now.

**Comment by karluiz** [comment]
`              if (!$('.typeahead').is(':visible')) {
                self.add(self.$input.val());
                self.$input.val('');
              }`

this works for me :)
