### ISSUE TITLE
get .val() to return duplicates value?

### ISSUE THREAD

**Issue by ayakashi** [bootstrap-tagsinput/bootstrap-tagsinput#391]
Is there a way to get the value of the tags, including duplicates, when i set allowDuplicates to true?

Currently from what I see through console.log (returning the val after tag is created), it only return one value of the duplicate. (tried both select multiple and input)

Example: 
Tags -> php bootstrap php. Value returned -> php, bootstrap
What I need:
Value returned -> php, bootstrap, php.

**Comment by lucknerjb** [comment]
The plugin is working as expected: https://jsfiddle.net/ws60becz/

If you are still having trouble, please re-open the issue. Closing for now.
