### ISSUE TITLE
copy and paste tags separated by semi-colons does not work

### ISSUE THREAD

**Issue by harrywang** [bootstrap-tagsinput/bootstrap-tagsinput#397]
We have added semi-colons as a confirm key, which works when you type the tags. 
confirmKeys: [13, 44, 59]

but when I try to copy and paste the following:

    adoption probability, social network, Bayesian learning; social influence; structural equivalence; entity similarity; confounding factor

it won't work and the result is shown as follows:

<img width="1212" alt="screenshot 2015-09-26 06 52 18" src="https://cloud.githubusercontent.com/assets/595772/10113820/42e9039c-641b-11e5-8f1a-4448a9fbcf9d.png">

We could not find any option to fix this. Any help on this? Thanks!

**Comment by harrywang** [comment]
anyone can help?

**Comment by lucknerjb** [comment]
Using v0.6.0, you can now pass in multiple delimiters via the "delimiterRegex" option. Ex:

element.tagsinput({
    delimiterRegex: /[;,]+/
})

The above would split on both the comma and semi-colon

**Comment by taniarv** [comment]
If you want to use the new delimiter in the value sent back to the browser, you also have to change the pushVal() function. 
```
    pushVal: function() {
      var self = this,
          val = $.map(self.items(), function(item) {
            return self.options.itemValue(item).toString();
          });
      self.$element.val(val.join(self.options.delimiter), true).trigger('change');
    }
```

**Comment by Twist-tracer** [comment]
delimiterRegex not working!
