### ISSUE TITLE
allowDuplicates not working?

### ISSUE THREAD

**Issue by KrunchMuffin** [bootstrap-tagsinput/bootstrap-tagsinput#398]
http://jsfiddle.net/naytkqfv/

itemsArray seems to get wiped out all the time.

**Comment by lucknerjb** [comment]
Your jsfiddle is out of date - are you still experiencing issues?

**Comment by KrunchMuffin** [comment]
updated and yes

http://jsfiddle.net/naytkqfv/1/

**Comment by lucknerjb** [comment]
Awesome then! Sorry about the late response but I'm glad you got it figured out

**Comment by KrunchMuffin** [comment]
You asked if I was still experiencing issues and I said yes. Not yes I am not. ☺

**Comment by lucknerjb** [comment]
Sorry, I read your comment wrong! I saw that you opened #419, let's continue on that ticket and leave this one was closed.
