### ISSUE TITLE
Calling .tagsinput() on input removes form-control style?

### ISSUE THREAD

**Issue by nhouse** [bootstrap-tagsinput/bootstrap-tagsinput#409]
When I call `.tagsinput()` on my input, the input is replaced with another one that is not styled correctly.

Video: http://www.screencast.com/t/Zi9NY7AUNVQ

How can I make the `tagsinput` input be styled like a normal bootstrap `form-control` input? (i.e. rounded corners, etc.).

**Comment by lucknerjb** [comment]
Did you load the CSS file? If you look at the examples page, the boxes are styled properly.

**Comment by lucknerjb** [comment]
Closing the issue for now. Please re-open if need be.
