### ISSUE TITLE
Feature request: Ability to reorder

### ISSUE THREAD

**Issue by machadoug** [bootstrap-tagsinput/bootstrap-tagsinput#412]
Greetings,

First of all, thanks for such a great plugin.

It would be great to have the ability to reorder tags using Drag and drop;

Best regards,

**Comment by lucknerjb** [comment]
I'm not sure this fits within the scope of the plugin. There are a bunch of really good re-ordering libs out there that you can plug in and connect to the tags as they are created and showed on the UI.
