### ISSUE TITLE
New repo location

### ISSUE THREAD

**Issue by lucknerjb** [bootstrap-tagsinput/bootstrap-tagsinput#413]
Hey all,

Tim has transferred the repository over to me, effective as of today. I'll be revisiting every issue and PR this evening and re-prioritizing work and working out some release schedules. Getting some contributors to get the changes rolling would be awesome!

So, if you've been waiting for a while to get an issue responded to or a PR merged in, it shouldn't take too long now to get those addressed.

Thanks to everyone for their patience!

**Comment by timschlechter** [comment]
Thanks again for all the work you put into this, @lucknerjb!  :+1: 

I wasn't able to put the time/effort it deserved into this project, apologies for this. I hope you can bring things further from here, good luck and have fun!

**Comment by creinero** [comment]
The examples link is dead since the change, could you please update it?

**Comment by lucknerjb** [comment]
We're sorting out the example link issues and will have that fixed soon! :)

**Comment by lucknerjb** [comment]
A couple of things:

- The final location for the repo is now the current one: https://github.com/bootstrap-tagsinput/bootstrap-tagsinput

- The links in the description and readme have been changed. Travis CI has also been updated to point to the right repo.

Anyone that is using the old repo - the one point to Tim's account - should not experience any issues as Github will redirect calls made via git and the browser to this new repo

Anyone just starting off with the plugin, please use this repo url :-)

**Comment by KrishnaPG** [comment]
Thank you for taking ownership. The CDN on JSDelivr is pointing to old version 0.5.0. from old repo.

Request you to kindly update the pionters there so that it can continue auto-updating to latest versions from the new repo. Here it is: http://www.jsdelivr.com/?query=bootstrap-tagsinput

**Comment by lucknerjb** [comment]
@KrishnaPG I've submitted a PR to jsdelivr to update the repo location so that the correct versions become available. Thanks for point that out!

https://github.com/jsdelivr/jsdelivr/pull/7825.

Leaving open for the time being

**Comment by lucknerjb** [comment]
@KrishnaPG jsdelivr seems to have been updated properly. It's showing v0.7.0 and should update with v0.7.1 which was released today. Closing this issue as I don't think it's needed anymore :-)

**Comment by KrishnaPG** [comment]
Thanks @lucknerjb
