### ISSUE TITLE
Please update examples

### ISSUE THREAD

**Issue by curiousdannii** [bootstrap-tagsinput/bootstrap-tagsinput#414]
Hi, I'm having a lot of trouble getting this to work. Using version [0.5.0 from cdnjs.com](https://cdnjs.com/libraries/bootstrap-tagsinput) I have been able to get the basic plugin working with Bootstrap 3.3.5. But I have not been able to get typeahead working, and it's really hard to diagnose what the problem is when your examples are using old versions of bootstrap, typeahead and this very plugin. Can you please update the examples to use the latest versions of everything? For typeahead that should be the fork at https://typeahead.js.org

It would also really help to have examples using typeahead but without Bloodhound. The docs say that you can use JQuery.get (and getJSON I assume) just in typeahead.source, or even just a plain array, but I haven't been able to get either working.

**Comment by lucknerjb** [comment]
Thanks for pointing that out. I'll make updating those a priority and try
and get them out asap

**Comment by curiousdannii** [comment]
Thanks! :)

**Comment by lucknerjb** [comment]
@curiousdannii Examples page has been updated - let me know if you're still having any issues and I'll see how I can help

**Comment by curiousdannii** [comment]
The link to bootstrap 2.3.2 in the header should be updated. Otherwise it looks good. If I have further troubles I'll make a new issue.
