### ISSUE TITLE
allowDuplicates not working

### ISSUE THREAD

**Issue by KrunchMuffin** [bootstrap-tagsinput/bootstrap-tagsinput#419]
http://jsfiddle.net/naytkqfv/1/

itemsArray seems to get wiped out all the time.

**Comment by lucknerjb** [comment]
@KrunchMuffin I'm not sure what your fiddle is showing as being an issue so I created a basic fiddle with allowDuplicates on. Can you update it to or fork it and update the new fiddle to represent the error you're experiencing?

http://jsfiddle.net/lucknerjb/a0LvLj7x/3/

**Comment by KrunchMuffin** [comment]
it probably mean to say allowDuplicates: false not working. it's been so long since I touched this.
I set it to false but it still allows me to add it.

http://jsfiddle.net/naytkqfv/2/

**Comment by lucknerjb** [comment]
Ah ok, I see what you mean now. The problem comes from this line in your callback:

```
$tag.hide.fadeIn();
```

If you remove it, the option works as it should. What are you trying to accomplish exactly with that piece of code? Or is this no longer an issue?

**Comment by KrunchMuffin** [comment]
Got it from the onTagExists option here
http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/

**Comment by lucknerjb** [comment]
Hmmm... you're right. That's weird then. Well, at least we've narrowed down the issue... now to figure out why the heck that piece of code is causing this!

**Comment by lucknerjb** [comment]
Haha, as if this escaped both of us. There is a missing "()" after the hide function call. I'll update the example.

**Comment by KrunchMuffin** [comment]
omg, can't believe i missed that. thx.

**Comment by lucknerjb** [comment]
Moving issue to release 0.7.1
