### ISSUE TITLE
Odd type error

### ISSUE THREAD

**Issue by gollenia** [bootstrap-tagsinput/bootstrap-tagsinput#42]
Hi,

I tried to include your plugin, but I ran into serious problems. Maybe you can help me.When I add the input box and asign the data-role without any javascript, everything works like a charm:

``` ruby
<input type="text" id="ingredientsList" data-role="tagsinput"/>
```

However, as soon as i add the JavaScript:

``` javascript
ingredientsInput = jQuery("#ingredientsList")
ingredientsInput.tagsinput();
```

I'm getting this error message:

```
Uncaught TypeError: Property 'undefined' of object #<b> is not a function 
```

Adding typeahead doesn't work aswell. I tried lots of variations, last one was this:

``` javascript
ingredientsInput = jQuery('#sidebar input')
        ingredientsInput.tagsinput();

        ingredientsInput.tagsinput('#sidebar input').typeahead({
             local: ['hallo', 'hihi']
        }).bind('typeahead:selected', jQuery.proxy(function (obj, datum) {  
            this.tagsinput('add', datum.value);
            this.tagsinput('#sidebar input').typeahead('setQuery', '');
        }, ingredientsInput));
```

which spilled out

```
Uncaught TypeError: Object #<b> has no method '#sidebar input' 
Uncaught TypeError: Property 'undefined' of object #<b> is not a function 
```

What could be the problem here? Please help me!

Greetings, Thomas

**Comment by alok111444** [comment]
I have read all Comments to finding out the solution , But I am not getting my solution, 

My console Errror is : TypeError: $(...).tagsinput is not a function, 
I had also tired removing data-role="tagsinput", But again its not working :)

**Comment by swn73** [comment]
yes,, I got the same problem with @alok111444  ,

 $(...).tagsinput is not a function,

**Comment by shekhar-ramco** [comment]
having the same problem.. was this solved?

**Comment by shekhar-ramco** [comment]
I got solved by refreshing the input element

`<input type="text" id="emailAddresses" ng-model="detailCtrl.instruction.ltaRequest.emailAddresses" tag-input="primary"  data-role="tagsinput">
            <script>
                $('#emailAddresses').tagsinput('refresh');
            </script>
            </input>`
