### ISSUE TITLE
document cancelConfirmKeysOnEmpty option

### ISSUE THREAD

**Issue by AdamFrey** [bootstrap-tagsinput/bootstrap-tagsinput#420]
The `tagsInput` function can take a `cancelConfirmKeysOnEmpty`, option which is set to true by default, but when set to false calls `.preventDefault` on the tag delimeter keydown event. I noticed this only by looking at the source code; the option appears nowhere on the [github.io documentation](http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/). I suggest adding it to the documentation, because it was a setting I needed to set to false in my application.

**Comment by lucknerjb** [comment]
Sorry, I meant to so that yesterday as it's a new option but didn't have
the chance to. It'll be done tonight :)

Glad you managed to figure it out though

**Comment by AdamFrey** [comment]
ha! I'm new to the library as of today. So I didn't even realize that you had put out a new release so recently or that this was new at all. Thanks!

**Comment by diakonos** [comment]
The code seems to do the opposite of what the documentation says, doesn't it?

Documentation:
> Boolean value controlling whether form submissions get processed when pressing enter in a field converted to a tagsinput (default: false).

[Code](https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/blob/master/dist/bootstrap-tagsinput.js#L474):
```
// If the field is empty, let the event triggered fire as usual
if (self.options.cancelConfirmKeysOnEmpty === false) {
  event.preventDefault();
}
```

Shouldn't the event be prevented if `cancelConfirmKeysOnEmpty` is true?
