### ISSUE TITLE
Comma character carried over to new tag input when used as separator

### ISSUE THREAD

**Issue by berniegp** [bootstrap-tagsinput/bootstrap-tagsinput#422]
## Steps to reproduce
In the first example on the example page, type:
`tag,`

## Problem
A comma is added to the input box for the next tag

## Where
#368 introduced this regression.

Offending code:

    self.$container.on('keypress', 'input', $.proxy(function(event) {
       var $input = $(event.target);

       if (self.$element.attr('disabled')) {
          self.$input.attr('disabled', 'disabled');
          return;
       }

       var text = $input.val(),
       maxLengthReached = self.options.maxChars && text.length >= self.options.maxChars;
       if (self.options.freeInput && (keyCombinationInList(event, self.options.confirmKeys) || maxLengthReached)) {
          // Only attempt to add a tag if there is data in the field
          if (text.length !== 0) {
             self.add(maxLengthReached ? text.substr(0, self.options.maxChars) : text);
             $input.val('');
          }

          // ------------- HERE --------------
          // If the field is empty, let the event triggered fire as usual
          if (self.options.cancelConfirmKeysOnEmpty === false) {
             event.preventDefault();
          }
       }

## Possible solution
Always call `event.preventDefault()` except when the key pressed is ENTER. The original intent was to allow form submission when ENTER is pressed in an empty input field.

**Comment by berniegp** [comment]
Related to #420. Setting cancelConfirmKeysOnEmpty to false fixes this since preventDefault is then always called.

**Comment by lucknerjb** [comment]
@berniegp The default for this new option should have been false instead of true. Thanks for the great bug repot btw! I've updated the default config and will push this with the next version.

**Comment by berniegp** [comment]
Sure thing!

I would argue that the behavior of cancelConfirmKeysOnEmpty = true is not optimal. In my opinion, a list of "non-cancellable keys" should be the only ones for which preventDefault() is not used. Perhaps ENTER and TAB? Otherwise any character used as a tag separator will be carried over to the next tag's input.

**Comment by gopalkumar315** [comment]
$("#input-tags").tagsinput({
                splitOn: ','
            });

**Comment by kenglang** [comment]
$("#input-tags").tagsinput({
splitOn: ','
});

Thanks, it's working for me.

**Comment by gopalkumar315** [comment]
kenglang Welcome
