### ISSUE TITLE
How to style context menu

### ISSUE THREAD

**Issue by enyosolutions** [bootstrap-tagsinput/bootstrap-tagsinput#434]
Hello, 

Great plugin ! 

How do i go about styling the content of the ajax autocomplete select. We have many sources of typeahead and we would like to sort them in tabs. 

thanks for your help.

**Comment by lucknerjb** [comment]
As of 0.7.0, there is default styling for the typeahead suggestions. You can use the basic styling file as a base to apply your own styling
