### ISSUE TITLE
typeahead uncaught TypeError: data[option] is not a function

### ISSUE THREAD

**Issue by dizzib** [bootstrap-tagsinput/bootstrap-tagsinput#436]
After adding a tag with typeahead 2.3.2 I'm seeing this error on the following line in bootstrap.js:

```
if (typeof option == 'string') data[option]()
```

It seems data['val'] is missing and I suspect it's related to fix #386.

**Comment by dizzib** [comment]
Ok, it seems typeahead 2.3.2 does not support jQuery#typeahead('val', val). This problem goes away when I use typeahead.js.

**Comment by dizzib** [comment]
My workaround is to add a dummy val() function to suppress the error:

    $.extend($.fn.typeahead.Constructor.prototype, {
        val: function(){}
    });

Then I applied guibirow's `return ''` fix for #331.

**Comment by andrews05** [comment]
Thanks for the workaround, had this same problem. Why have you closed the issue?

**Comment by dizzib** [comment]
Because I found a workaround. I'll reopen so it can be properly fixed.

**Comment by megapctr** [comment]
I'm not going to admit how much time I spent debugging this crap.

**Comment by megapctr** [comment]
Here's an improved workaround that will actually modify the input.
I wish I could not use that `setTimeout`, but without it the input value would be modified again to display selected item - we need to modify the input _after_ this happens.
```
$.extend($.fn.typeahead.Constructor.prototype, {
    val: function (value) {
        setTimeout(function () {
            this.$element.val(value);
        }.bind(this));
    }
});
```

**Comment by merolhack** [comment]
It need to validate if val exists in de data array:
```javascript
if ( typeof data[option] !== 'undefined' ) {
```
Or it thorwn an error:
```javascript
Uncaught TypeError: Cannot read property 'apply' of undefined
```
> (anonymous function) @ bootstrap3-typeahead.min.js:4
> m.extend.each @ jquery-1.11.3.min.js:2
> m.fn.m.each @ jquery-1.11.3.min.js:2
> $.fn.typeahead @ bootstrap3-typeahead.min.js:1b.add @ bootstrap-tagsinput.min.js:6
> e.$input.typeahead.a.extend.updater @ bootstrap-tagsinput.min.js:6
> Typeahead.select @ bootstrap3-typeahead.min.js:1
> Typeahead.click @ bootstrap3-typeahead.min.js:1
> m.isFunction.e @ jquery-1.11.3.min.js:2
> m.event.dispatch @ jquery-1.11.3.min.js:4
> r.handle @ jquery-1.11.3.min.js:4

**Comment by axit-joost** [comment]
@merolhack your solution works. May I suggest that you open a seperate issue and create a PR for this fix?
