### ISSUE TITLE
No focusClass option

### ISSUE THREAD

**Issue by KrunchMuffin** [bootstrap-tagsinput/bootstrap-tagsinput#439]
According to the docs there is a `focusClass` option. Checked the js file and there is no reference to `focusClass`.

**Comment by lucknerjb** [comment]
Thanks for pointing that out. The dist files were not properly built with the last release so I took care of that.

**Comment by bernatgy** [comment]
I don't know what did you do to fix this, but this feature does not work right now at all, and the website still suggests that this option is there. :)

**Comment by marcodelpercio** [comment]
I agree this option is in the documentation and yet it doesn't appear to be in the generated dist js file.
