### ISSUE TITLE
keydown event is not reliable for Chinese punctuation, would you please change it to keyup?

### ISSUE THREAD

**Issue by bianjp** [bootstrap-tagsinput/bootstrap-tagsinput#440]
My customers are Chinese, so I want that when the user inputs Chinese comma "，", it also triggers the confirm tag operation like English comma ",".

But I found that the keydown event is inconsistent and not reliable for Chinese punctuation. Pressing Chinese punctuation keys do not fire keydown event (Firefox 42), or fires keydown event but with event.which = 229 (Chrome 46, IE 11). 229 is produced by many other keys so it's not able to determine which key is pressed.

keyup event doesn't have this issue. Pressing Chinese comma "，" just fires keyup event with event.which = 188, the same as English comma.

You can visit [jQuery keydown](http://api.jquery.com/keydown/)(the bottom of the page) to test. [Google pinyin](http://www.google.com/intl/zh-CN/ime/pinyin/) is an available Chinese input method.

Not sure whether users of other languages suffer the problem or not.

Would you please change the event listened to keyup, or add an  option to allow users to specify what event to listen?

Is a pull request welcome?

**Comment by bianjp** [comment]
I have made a [test](https://github.com/bianjp/bootstrap-tagsinput/commit/f878f8676f5484694bd9d499ffdca7aadc534307) and found that just changing the keyboard event wouldn't do the trick.

I'll look into it futher when I have time.

**Comment by lucknerjb** [comment]
@bianjp Let me know if you find a solution. If it's something that easy to accommodate and could come in handy to others as well, we can consider making a change.

**Comment by fani8nb** [comment]
@lucknerjb @bianjp Any progress on it latter on ?

**Comment by bianjp** [comment]
@fani8nb No. Currently I'm not doing any frontend development.
