### ISSUE TITLE
How to set TEXT if i set the DisplayValue to an ID's?

### ISSUE THREAD

**Issue by BogelDR** [bootstrap-tagsinput/bootstrap-tagsinput#442]
Hey this plugin is so great and i'd love to use this for my projects and i get stuck when i use this plugin. I trying to show the **text** of the data as a text and the **id** of the data as a value for input text, which is my JSON data is like this:

``` javascript
[{"id":3,"text":"aut"},{"id":6,"text":"aut"}]
```

and my Javascript code:

``` javascript
var tags = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  remote: {
    url: 'api/v1/tags/%QUERY',
    wildcard: '%QUERY'
  }
});

tags.initialize();

$('#tags').tagsinput({

    typeheadjs: {
      name: 'tags',
      displayKey: 'text',
      valueKey: 'id',
      source: tags.ttAdapter()
    }
});
```

i've trying to use **itemValue:** and **itemText** Option, but if i set that options in my javascript function, the users cant add a new tag. Is that possible if i show the **text** on the input form?

**Comment by frankazoid** [comment]
shouldn't it be 'type**a**headjs: {' instead of 'typeheadjs: {' ? seems like 'a' is missing
