### ISSUE TITLE
Issue on typeahead + tag when user goes off focus (onblur)

### ISSUE THREAD

**Issue by waltonryan** [bootstrap-tagsinput/bootstrap-tagsinput#446]
We're having this issue with the library and I was able to recreate it on your demo site, where after the user has created a tag (the typeahead version) and tabs off the input, the text of the tab is displayed after the tab. 

<img width="1033" alt="screen shot 2015-12-09 at 3 55 05 pm" src="https://cloud.githubusercontent.com/assets/1802050/11702735/d032f58a-9e8d-11e5-9db2-381def1c7551.png">

Are you aware of the issue? Do you have an idea on how to fix it? Thanks!

**Comment by AlexandraColdea** [comment]
Hi, 
I was having the same problem. I am using bootstrap 2.3.2.
I managed to temporarily get around it by removing the return statement from the following lines of code in bootstrap-tags-input.js :

updater: function (text) {
            self.add(this.map[text]);
            return this.map[text];
 },

This is the commit that added the return statement in the first place: https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/commit/03e6ce0785268d6f89aa11152f8cda815b95b1f0 
Therefore, I think that this might not work with bootstrap 3.

**Comment by dongyeonlee** [comment]
Hi,
I  also having the same problem.
My solution is
<code>
$('input').on('focusout',function(event){
$('.typeahead').typeahead('destroy');
});
</code>

But this solution is not good

**Comment by AlbinoDrought** [comment]
The feature is disabled while using typeahead:

	// HACK: only process on focusout when no typeahead opened, to
	//       avoid adding the typeahead text as tag
	if ($('.typeahead, .twitter-typeahead', self.$container).length === 0) {
		self.add(self.$input.val());
		self.$input.val('');
	}

Without this function, I think the tag input will be confusing to end-users (tags left as text do not count on form submit). To make this work for my solution, I did the following:

	$(".twitter-typeahead input").on('focusout', function() {
		var elem = $(this).closest(".bootstrap-tagsinput").parent().children("input").last();
		console.log(elem);
		elem.tagsinput('add', $(this).val());
		$(this).typeahead('val', '');
	});

This finds the typeaheadjs input (that bootstrap tagsinput called .typeahead on) and attaches to focusout. When triggered, it traverses the DOM tree upwards to find the bootstrap tag input. From there, it attempts to find the "original" input that you called .tagsinput on.

I am not using a select element, so it will not work with that (change input to select). I am not using data-role, but it may work with that.

Here is an excerpt how my code looks if you are having issues:

	<div class="form-group row">
		<label class="col-md-2 control-label" for="video_tags">Tags</label>
		<div class="col-md-10">
			<input id="video_tags" name="video_tags" type="text" placeholder="" class="form-control input-md"></input>
		</div>
	</div>
	
	<script type="text/javascript">
		$("#video_tags").tagsinput({
			cancelConfirmKeysOnEmpty: false,
			addOnBlur: true,
			typeaheadjs: {
				name: 'existingTags',
				source: existingTags.ttAdapter()
			}
		});
		
		$(".twitter-typeahead input").on('focusout', function() {
			var elem = $(this).closest(".bootstrap-tagsinput").parent().children("input").last();
			console.log(elem);
			elem.tagsinput('add', $(this).val());
			$(this).typeahead('val', '');
		});
	</script>

**Comment by rtselva03** [comment]
Hi,
i need to clear input field on focus out if its not tagged,
 pls help me out from this guys
Thank you.....

**Comment by paulschwarz** [comment]
Without using jQuery selectors all over the place:
```javascript
        // Returns an array of TagInput instances
        var widgets = $el.tagsinput({
            typeaheadjs: {
                // ...
            },
        });

        // Add tag on blur https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/446
        widgets.forEach(function(widget) {
            var input = widget.input();

            input.blur(function() {
                widget.add(input.val());
                input.typeahead('val', '');
            });
        });
```

**Comment by saurabhverma2892** [comment]
I fixed it by changing my typeahead.js.

function resetInputValue is called on blur, which is 
`resetInputValue: function resetInputValue() {
                this.setInputValue(this.query);
            },`

edit this function as:
`resetInputValue: function resetInputValue() {
                this.setInputValue("");
                //this.setInputValue(this.query);
            },`

**Comment by nezirz** [comment]
This worked in my case  solution from @itsprdp here:
["https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/236"](https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/236)

A better way to clear the typeahead input after adding the tag.

self.$input.typeahead('val', '');

Add this line to the end of the add() function after line number 149 in the src file https://github.com/TimSchlechter/bootstrap-tagsinput/blob/master/src/bootstrap-tagsinput.js

Ref: twitter/typeahead.js#233

**Comment by bartclaeys** [comment]
This worked for me, with jQuery:

```
$('.my_input_field').blur(function() {
	$(this).val('');
});
```
