### ISSUE TITLE
confirmKeys don't work with objects as tags

### ISSUE THREAD

**Issue by tim-peterson** [bootstrap-tagsinput/bootstrap-tagsinput#449]
The default `confirmKeys`, namely enter = 13 or comma = 188, don't appear to work out of the box with the tags being obejcts. They do work if the tags are strings. 

If you look [at the demos](http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/), the "Typeahead" example allows tag creation with the default `confirmKeys`, enter or comma, but the "Objects as Tags" example right below it does not.

Any idea how to make the `confirmKeys` work with object tags?

The demos should be updated as they use v0.4.2 whereas the repo is on v0.7.1.

**Comment by tim-peterson** [comment]
I fixed this issue and documented it here: http://stackoverflow.com/questions/34454269/bootstrap-tagsinput-confirmkeys-dont-work/34484005#34484005

Feel free to pull [my forked library](https://github.com/doorofclubs/bootstrap-tagsinput).

**Comment by lucknerjb** [comment]
@tim-peterson I'll update the demo page and have a look at the issue you mentioned. I know it's a little late but hopefully I can still be of assistance.

**Comment by tim-peterson** [comment]
Thanks @lucknerjb , that will help others!

**Comment by And-Sm** [comment]
+1, waiting for fix

**Comment by ant-s** [comment]
Thanks @tim-peterson, this has been very helpful.

**Comment by Tom29** [comment]
@tim-peterson tested your folked version (examples) but didn't work
