### ISSUE TITLE
bootstrap-tagsinput with typeahead

### ISSUE THREAD

**Issue by koshak01** [bootstrap-tagsinput/bootstrap-tagsinput#452]
bootstrap3-typeahead.js:434 Uncaught TypeError: Cannot read property 'apply' of undefined(anonymous function) @ bootstrap3-typeahead.js:434n.extend.each @ jquery.js:374n.fn.n.each @ jquery.js:139$.fn.typeahead @ bootstrap3-typeahead.js:427TagsInput.add @ bootstrap-tagsinput.js:167self.$input.typeahead.$.extend.updater @ bootstrap-tagsinput.js:328Typeahead.select @ bootstrap3-typeahead.js:79Typeahead.keyup @ bootstrap3-typeahead.js:367n.isFunction.f @ jquery.js:512n.event.dispatch @ jquery.js:4435r.handle @ jquery.js:4121

((((( 

data[option].apply(data, Array.prototype.slice.call(arg ,1));

option = 'val'

data not null

data['val'] null ((((

**Comment by lucknerjb** [comment]
Can you provide code samples of your implementation?

**Comment by davidkonrad** [comment]
See http://stackoverflow.com/a/35489978/1407478 and https://github.com/bassjobsen/Bootstrap-3-Typeahead/pull/199  ...Two minor fixes does it, but there should be looked into how bootstrap-tagsinput uses the good old bootstrap 2 typeahead.  As it is now, it cannot be used as in the docs, have not had the time to look into it myself (and is not familiar with tagsinput)
