### ISSUE TITLE
need custom $tag html structure

### ISSUE THREAD

**Issue by virtuecai** [bootstrap-tagsinput/bootstrap-tagsinput#453]
var $tag = $('<span class="tag ' + htmlEncode(tagClass) + (itemTitle !== null ? ('" title="' + itemTitle) : '') + '">' + htmlEncode(itemText) + '<span data-role="remove"></span></span>');

need custom $tag html structure

**Comment by lucknerjb** [comment]
What's the use case for this exactly?

**Comment by wongcode** [comment]
+1 for this. I am running into a situation to handle text overflow of a tag. I added ::after and ::before pseudo elements to your standard tag markup which I don't want to hide with overflow: hidden. I only want to hide the over inside, which is the itemText. It would help if I can control the markup of the tag itself.

**Comment by antiphp** [comment]
+1 have language dropdown, tag should be the flag icon
