### ISSUE TITLE
Need custom container tag or custom class for container

### ISSUE THREAD

**Issue by ccrims0n** [bootstrap-tagsinput/bootstrap-tagsinput#455]
There is a need of custom container tag or way to add custom classes to container tag.

Currently, it's hardcoded as:

```
this.$container = $('<div class="bootstrap-tagsinput"></div>');
```

An option can be provided for the same.

**Comment by eromoe** [comment]
+1
I'd like use it in a form, so `form-control`  must be add to the container class.
And container need to have `height:auto !important;`

**Comment by 73sl4** [comment]
I'll generate a Pull Request.

**Comment by fusionbeam** [comment]
+1

**Comment by KeitIG** [comment]
+1
