### ISSUE TITLE
disable keyboard input?

### ISSUE THREAD

**Issue by joeylu** [bootstrap-tagsinput/bootstrap-tagsinput#457]
I'm trying to create a scenario that user can only add tags by using the select options, is there anyway that I can disable the user's keyboard input? tks

**Comment by lucknerjb** [comment]
Have you tried making the input field "disabled"?

**Comment by sumit-sharma** [comment]
I tried to disable input by entering following code
`
$(function(){
$('.bootstrap-tagsinput input').attr("disabled", "disabled"); 
});
`
but still can't disable direct keyboard entering on tagsinput. Do anyone know the solution please reply?

**Comment by sumit-sharma** [comment]
I got same problem it worked for me  by making readonly
