### ISSUE TITLE
convert to tags on blur

### ISSUE THREAD

**Issue by RicardoGeek** [bootstrap-tagsinput/bootstrap-tagsinput#468]
If I have an input with an id, and I dont hit any of the confirm keys the plugin will not pass the values to my input and will keep the values on its own input.

Solution is converting everytihng in the textbox to a tag on blur.

help please.

**Comment by pdobrigkeit** [comment]
I had the same problem and I used this hacky whacky way to do it for now. Maybe this helps some or someone can improve on it.

    var tagInput = $('#field.typeahead').tagsinput();
    
    var tagInputInput = tagInput[0].$input;
    tagInputInput.blur(function() {
        var value = tagInputInput.val();  
        tagInputInput.val('');
        $('#field.typeahead').tagsinput('add', value);
    });

**Comment by emsuryadi** [comment]
You can also add event listener inside `build` function [here](https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/blob/41fe4aa2201c4af4cfc4293fa3fc8260ad60bf35/src/bootstrap-tagsinput.js#L282).
```
// Confirm on blur
self.$container.on('focusout', 'input', $.proxy(function(event) {
    var text = $(event.target).val();
    if (text != "" && text != undefined && text != null) {
        self.add(text);
    }
}, self));
```
