### ISSUE TITLE
typeahead not working with typeahead.js and broken with boostrap3-typeahead

### ISSUE THREAD

**Issue by alexge233** [bootstrap-tagsinput/bootstrap-tagsinput#470]
Hello!

Many thanks for the lovely library.
I'm having an issue which I'm not so sure how to solve.

I've tried with your recommendation (typeahead.js) and it doesn't work (at all).
Trying with [boostrap3-typeahead](https://github.com/bassjobsen/Bootstrap-3-Typeahead) works:

``` js
    $("#tags").tagsinput({
        typeahead: {
            source: function(query) {
                return $.get('/ajax/keywords');
            }
        },
        maxTags: 5,
        maxChars: 32,
        allowDuplicates: false,
        tagClass: 'label label-primary'
    });
```

However, if say this is the result of the ajax call (the auto-suggestion array):
`["Amsterdam","Washington","Sydney","Beijing","Cairo"]`
1. When I type "Ams" the typeahead comes up.
2. I click on it
3. The tag "Amsterdam" is now in the field
4. The text "Amsterdam" is still left in the input field.

Manually deleting it some times deletes the tag, but regardless, it renders the point of using auto-suggestions mute.

I can see that after clicking on the autsuggestion, this DOM element still remains there:

```
<span class="tag label label-primary">Amsterdam<span data-role="remove"></span></span>
<input type="text" placeholder="" size="3">
```

I am guessing this is probably related to `bootstrap3-typeahead` rather than `boostrap-tagsinput`, so I've also [opened an issue there](https://github.com/bassjobsen/Bootstrap-3-Typeahead/issues/208).

I have tried for the better part of a night to make it work, even hacking into it:

``` js
    $("#tags").on('itemAdded', function(event) {
        //console.log(event.item);
        var field = $(".bootstrap-tagsinput").children('input[type="text"]').first();
        if (field){
            console.log(field[0]);
            field.attr('size','0');
            field.val('');
        }
    });
```

But it just won't have it!

Reverting back to [simple typeahead.js examples](http://twitter.github.io/typeahead.js/examples/) is not working either, I get nothing at all!

Apart from setting the typeahead source, do I need to do anything else?

**Comment by Phisherman** [comment]
Hi,

You should try typeahead.js again. For me it works perfectly. I had the same problem with the staying text in bootstrap3-typeahead.

**Comment by alexge233** [comment]
Hi Phiserman, would you be so kind to provide a minimal example using typehead.js ? I can't get it to work at all, my ajax data is there, no errors in the console or anything, but there is no typehead or autosuggest showing.

**Comment by Phisherman** [comment]
I'll do it tomorrow!

**Comment by Phisherman** [comment]
@alexge233 Here you go: https://jsfiddle.net/by4asnh2/3/

**Comment by boeserwolf** [comment]
Ran into the same issue as I tried to use typeahead.js with bootstrap-tagsinput-angular.

The solution is to set the options to { typeahead**js**: { source: ... } } for Bootstrap 3.x, **not** { typeahead: { source: ... } } 

The AngualrJS directive 'bootstrapTagsinput' can be changed accordingly to make it work:

        ...
        select.tagsinput(scope.$parent[attrs.options || ''] || {
          typeaheadjs : {
            source   : angular.isFunction(typeaheadSource) ? typeaheadSource : null
          },
          ...

**Comment by alexge233** [comment]
@Phisherman tons of thanks, this actually works.
@boeserwolf I'll give this a try, thanks for the suggestion.

**Comment by Phisherman** [comment]
@alexge233 You're welcome.

**Comment by lamsion** [comment]
It works by following code change in the source code:

> if (this.autoSelect || val) {
        var newVal = this.updater(val);
        // Updater can be set to any random functions via "options" parameter in constructor above.
        // Add null check for cases when updater returns void or undefined.
//        if (!newVal) {
          newVal = '';
//        }
        this.$element
          .val(this.displayText(newVal) || newVal)
          .text(this.displayText(newVal) || newVal)
          .change();
        this.afterSelect(newVal);
      }

**Comment by fahadali916** [comment]
I also faced this issue and I got the solution from #522 . You can find different suggestions, but the one that worked for me was the one I [posted](https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/522#issuecomment-255160516) on that issue.
