### ISSUE TITLE
Keep input on focus after pressing tab

### ISSUE THREAD

**Issue by brunoDegaspare** [bootstrap-tagsinput/bootstrap-tagsinput#473]
After inserting a tag, I have to click back on the input in order to insert another tag. I couldn't find any option to keep the input on focus after pressing tab to insert a tag. Is it any option for that?

**Comment by Phisherman** [comment]
How are you inserting a tag? Typing in `,` after each tag did the trick for me.

**Comment by jbx1** [comment]
A coma doesn't work well. It starts the next tag with a coma (at least it does it in my case when using typeahead and freeInput).
Adding the tab character as one of the confirmKeys, with character 9, doesn't work either, because it moves focus to the next field in the form.
The enter key (13) submits the whole form. 

This component shouldn't propagate the key strokes that are set as confirmKeys.

**Comment by fbardel** [comment]
Hello, same problem, "Enter" key post my form.
Thanks by the way ^^

**Comment by mistercam** [comment]
I'm having this same issue now. I've added the tab key (9) to _confirmKeys_, but pressing tab causes a loss of focus. It'd be nice if the cursor remained in the tags field.

**Comment by charlie-wasp** [comment]
Can't we just use `event.preventDefault` for `confirmKeys`? I used it as a hotfix in my project, just added this line like that:

```
      self.$container.on('keypress', 'input', $.proxy(function(event) {
         var $input = $(event.target);

         if (self.$element.attr('disabled')) {
            self.$input.attr('disabled', 'disabled');
            return;
         }

         var text = $input.val(),
         maxLengthReached = self.options.maxChars && text.length >= self.options.maxChars;
         if (self.options.freeInput && (keyCombinationInList(event, self.options.confirmKeys) || maxLengthReached)) {
            // Only attempt to add a tag if there is data in the field
            if (text.length !== 0) {
               self.add(maxLengthReached ? text.substr(0, self.options.maxChars) : text);
               $input.val('');
               event.preventDefault(); // <<<<<< HERE
            }

            // If the field is empty, let the event triggered fire as usual
            if (self.options.cancelConfirmKeysOnEmpty === false) {
               event.preventDefault();
            }
         }
```

Can it have some unwanted consequences? That fixed usage of enter key and comma, tab wasn't tested

**Comment by lwm** [comment]
For any other poor soul, lost on the high seas of abandoned side project, I used https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/302#issue-58057546 and https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/473#issuecomment-237147283 and added 9 for my `confirmKeys`, and I could tab away to my hearts content.

**Comment by nquocvuong** [comment]
I have another solution to "Keep input on focus after pressing tab"
```javscript
$(document).ready(function() {
  $("#tags").tagsinput({
    trimValue: true,
    confirmKeys: [9,188]
  });
$("#tags").closest('form').find('input').on('keydown',function (e) {

  if (e.which == 9)
    {
      $("#node_tags").tagsinput('add',$(this).val());
      $(this).val("");
      e.preventDefault();
    }

})

})

$("#tags").closest('form').find('input') // need replace, this js find the input element generated by bootstrap-tagsinput 
```
My html:

```html
<form class="form-inline">
  <label class="sr-only" for="tags">Tags</label>
  <select class="tags" multiple="multiple" name="node[tags][]" id="tags" style="display: none;"></select>
</form>
```

**Comment by ymps3502** [comment]
I think this solution is the better way, but you have to give id to every inputs.
```javascript
$('#form').on('keypress', function(e) {
  var keyCode = e.keyCode || e.which;
  if ($(e.target).is('*:not([id])') && keyCode === 13) {
    e.preventDefault();
    return false;
  }
});
```

**Comment by coloftech** [comment]
this work for me:

`
$(document).on('keydown','input[size="1"]',function(e){
	
	if(e.which === 13){
		$(this).focus();
	}
})`

**Comment by planetgreensolutions** [comment]
This works for me for tab and enter key
$('body').on('keydown','.bootstrap-tagsinput input' ,function(e) {
		var keyCode = e.keyCode || e.which;
		if (keyCode === 9 || keyCode === 13 ) {
			e.preventDefault();
			$("#tags").tagsinput('add',$(this).val());
			$(this).val('');
			return false;
		}
	});
