### ISSUE TITLE
TagsInput behaving odd

### ISSUE THREAD

**Issue by kerolol** [bootstrap-tagsinput/bootstrap-tagsinput#476]
I have a multiple select as a TagsInput:

```
<select multiple data-role="tagsinput" placeholder="Tags (i.e. 'Competition', 'Fun training' etc.) Separate with commas">
</select>
```

When I start to add tags, it automatically adds another comma and the input is on a new line, like in the picture.

![tagsinput](https://cloud.githubusercontent.com/assets/1997358/13728627/e7ba50fa-e91e-11e5-94ff-846ed22daab8.png)

**Comment by jakenoble** [comment]
Did you find a fix?
