### ISSUE TITLE
Residual input lost when tabbing out of input

### ISSUE THREAD

**Issue by edwh** [bootstrap-tagsinput/bootstrap-tagsinput#477]
Thanks for a great bit of code.

Ideally if you have freeInput, then any remaining text would be converted into a tag when the field loses focus - is there a way to do that?

The background is that I've got an input where I've set to allow freeInput, and my fingers are used to tabbing to the next field.  Any residual text is effectively is lost from the input as retrieved by tagsinput('items') - it's not been converted into a tag, and doesn't show.

I've tried setting confirmKeys to include 9 to block the tab, but that doesn't seem work, and wouldn't be ideal.

**Comment by lvpro** [comment]
Did you ever find an answer for this?  I need it as well.
