### ISSUE TITLE
How to list all items when input focus?

### ISSUE THREAD

**Issue by TangMonk** [bootstrap-tagsinput/bootstrap-tagsinput#482]
Thanks, I am try to search on google, but not works

**Comment by lucknerjb** [comment]
Can you explain your use case a little better? Which items are you referring to? The tags? Json data?

**Comment by ronaldohoch** [comment]
I think he wants to do the same as below, 'cause i want the same.
The image uses other plugin.

![image](https://cloud.githubusercontent.com/assets/2287371/24771372/cb30baee-1ae3-11e7-85e3-0e9658a1f490.png)
