### ISSUE TITLE
Any plan to make it for textarea? 

### ISSUE THREAD

**Issue by Multi-Thinker** [bootstrap-tagsinput/bootstrap-tagsinput#484]
I'm building application like iconfinder / flaticon the tags input is in `table`, the full `td` is the size of image 512x512 a line of `input` doesn't seem nice, even if i try to expand the size with `min-height:100%` the tags go in middle of `input type='text'` and all empty space on top and bottom are useless. any suggestions?

**Comment by lucknerjb** [comment]
Would something like this work? You basically set the size of the wrapper div instead of manipulating the input field.

If not, can you provide a JSFiddle?

![screen shot 2016-05-11 at 4 21 11 pm](https://cloud.githubusercontent.com/assets/832836/15195140/82708da0-1794-11e6-92ad-728d5e1d9fd2.png)

**Comment by Multi-Thinker** [comment]
Please have a look on this [fiddle](https://jsfiddle.net/6070k2je/) I've reproduce the problem i am facing, the tags and the `input` cursor are in middle, what i want is to make them natural like `textarea` or like that image you have display above.. Please let me know where i am doing wrong, and if there is any possibility for `textarea` tagsinput update

Thanks, looking forward for your response.
