### ISSUE TITLE
tag with double quotes

### ISSUE THREAD

**Issue by davidaniel** [bootstrap-tagsinput/bootstrap-tagsinput#485]
When creating a tag with a double quote (") like `height 8"` I got this error  `jquery.js:1458 Uncaught Error: Syntax error, unrecognized expression: option[value="height 8""]`

**Comment by lucknerjb** [comment]
We'll have to escape double quotes in tags with something like this before it gets added to the DOM

```
tag = tag.replace(/"/g, '\\"');
```

**Comment by khoa24988** [comment]
Should be:
$('option[value="' + htmlEncode(itemValue).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"]', self.$element).length
Instead of:
$('option[value="' + htmlEncode(itemValue).replace(/"/g, '\\"').replace(/\\/g, '\\\\') + '"]', self.$element).length

**Comment by flybeach** [comment]
hey I am using last version, but this is happening yet, let me know how I could work out this issue?
I look forward your quick response.

**Comment by khoa24988** [comment]
In bootstrap-tagsinput.js

Try replace:
$('option[value="' + htmlEncode(itemValue) + '"]', self.$element).length
with
$('option[value="' + htmlEncode(itemValue).replace(/\/g,
'\\').replace(/"/g, '\"') + '"]', self.$element).length

**Comment by flybeach** [comment]
Thanks for your sincere help, it solved this issue, but wondering why you guys didn't update actual hosted file yet with latest version.

**Comment by khoa24988** [comment]
I dont know, may be they busy with new version :)

**Comment by wuzupko** [comment]
You have to use HTML tags:
 $('option[value="' + htmlEncode(itemValue).replace(/"/g, '&quot').replace(/\\/g, '\\\\') + '"]', self.$element).length

**Comment by maxlibin** [comment]
use this >
$('option[value="' + htmlEncode(itemValue).replace(/"/g, '&quot').replace(/"/g, '\"') + '"]', self.$element).length

**Comment by TOuhrouche** [comment]
Faced the same issue and fixed it by using double quotes to denote strings instead of strings:
```
      var optionExists = (
        $("option[value='" + encodeURIComponent(itemValue) + "']", self.$element).length ||
        $("option[value='" + htmlEncode(itemValue) + "']", self.$element).length
      );
```
