### ISSUE TITLE
sorting issue 

### ISSUE THREAD

**Issue by yogeshsaroya** [bootstrap-tagsinput/bootstrap-tagsinput#486]
Hi 

Nice plugin but it have issue on sorting. 

when i press D, it will show this result > 
![sort](https://cloud.githubusercontent.com/assets/718025/15075951/d476d074-13c4-11e6-91c9-24fca325ce8d.jpg)

but it should be like this > 
![correct](https://cloud.githubusercontent.com/assets/718025/15076016/2ab23e9c-13c5-11e6-9e8f-293e6b3fa9e1.jpg)

How to fix it ? 

Thanks

**Comment by lucknerjb** [comment]
Can you paste your code?. JsFiddle would be great if possible
