### ISSUE TITLE
Converting Text to Tags and Allowing Free Text

### ISSUE THREAD

**Issue by ecopk** [bootstrap-tagsinput/bootstrap-tagsinput#487]
Hi Team,

I was trying to use Bootstrap-Tagsinput with jQuery Autocomplete Multiple (JQuery Autocomplete Multiple is available here: http://jqueryui.com/autocomplete/#multiple-remote)

As per my scenario, I have to allow the end-user to be able to type free text and select autocomplete text as well. When I use, Bootstrap Input Tags on the Textbox. It converts everything into Tags whereas I only want it to select specific parts of the text via jQuery.

> **Example Scenario:**

**is the doll available in "red" and "blue" colors?**
Now, the words "red" and "blue" will come from jQuery autocomplete whereas the rest is free text entered by the user. 

> **Challenge:**

I want to covert the words "red" and "blue" in my sentence to tags whilst the rest should remain as free text.

Could anyone suggest the jQuery code I should be using to fix this?

Thanks,

**Comment by lucknerjb** [comment]
This plugin is not the one you are looking for as, like you said, everything gets converted into a tag. You could probably make use of a moving autocomplete field and use CSS to make it "look" like a tag but that kind of architectural design is way beyond the scope of this plugin.

Good luck!

**Comment by ecopk** [comment]
Sounds like a good advise.
Have you come across anything similar from CSS?
Thanks,
