### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by leamlidara** [bootstrap-tagsinput/bootstrap-tagsinput#489]
I have my code below but I don't know what is wrong with this code. Please feel free to edit me, thanks!
![untitled](https://cloud.githubusercontent.com/assets/10239131/15157028/f9353778-1713-11e6-978a-83019a196db3.png)

**Comment by lucknerjb** [comment]
Can you:
* provide the final code that gets generated? Does the element exist on the page?
* Do you get any console errors? What exactly does "It's not working" mean?
