### ISSUE TITLE
Init input from ajax response?

### ISSUE THREAD

**Issue by CosmicBoris** [bootstrap-tagsinput/bootstrap-tagsinput#492]
Hello, I`m using ajax to load new input elements after page completely loaded,
I tried  bind this new elements to tagsinput by evaluating script from response:
    `$(function() {
               $("input[data-role=tagsinput], select[multiple][data-role=tagsinput]").tagsinput();
    });`
but I getting error: TypeError: $(...).tagsinput is not a function
the only solution I found is to include all code from bootstrap-tagsinput.min.js to `<script>` tag and evaluate it. I believe must be a better solution.

**Comment by JosKrause** [comment]
You should bind it when the ajax callback completes, and not just on page load, since they are two completely different matters.

**Comment by CosmicBoris** [comment]
Hi @JosKrause maybe You can show how to do that programmatically?
