### ISSUE TITLE
Stripping out special characters does not happen on 'Add'

### ISSUE THREAD

**Issue by FaithInMotion** [bootstrap-tagsinput/bootstrap-tagsinput#494]
I do not want to allow special characters. I have utilized 'beforeItemAdd' and stripped the characters there from the event.item itself.

```
event.item = event.item.replace(/[^a-z0-9\s]/gi, '');
```

We are also saving the tags to the database as well as creating a quick search on creation of tag.

So far, when a tag is created, the database gets special characters stripped out, as does the quick links on search (buttons created as a tag is created that populate a filter input field for "quick searching"). However, the tag itself retains all special characters until the page is refreshed. This is resulting in an inability to create a new tag and then immediately search it - it is unsearchable until the page is refreshed.

I have tried using the tagsinput('refresh') command in place and it is doing nothing. #

**Comment by Sentence** [comment]
+1

**Comment by FaithInMotion** [comment]
I'm going to close this as I'm tired of seeing it in my GitHub - I'm guessing now that 2017 is almost up this just isn't supported anymore.
