### ISSUE TITLE
All inputs in form change to bootstrap-tagsinput

### ISSUE THREAD

**Issue by upsson** [bootstrap-tagsinput/bootstrap-tagsinput#499]
Im trying to get all the items in the TagList using
`$("input").tagsinput('items')`

But instead it converts all my input elements 

> div  bootstrap-tagsinput class

**Comment by bernatgy** [comment]
This is not a bug. You should use a direct selector for your input. eg. #idOfYourInput
Right now, you are selecting all of the inputs on your page.
