### ISSUE TITLE
Duplication of tags that contains "\" character

### ISSUE THREAD

**Issue by AlexDEVpro** [bootstrap-tagsinput/bootstrap-tagsinput#502]
If the select contains options with the symbol **\\**, these options are duplicated in the select after the initialization of the control.
In fact there is no duplication, but adding of one more tag. If there are two of the same tags "HOME-PC\\Alex", the third will be added on initialization of the control even if duplicates are not allowed.

**Comment by reverland** [comment]
#485 , all " and \ will crash the program for string interpolation
