### ISSUE TITLE
Typeahead issue

### ISSUE THREAD

**Issue by cr1t** [bootstrap-tagsinput/bootstrap-tagsinput#507]
Wonder if anybody had issues with typeahead, The hint keeps overflowing. I don't see this in examples. Something with the hint thats the problem.
![typeahead](https://cloud.githubusercontent.com/assets/4394765/16617670/485baef2-4385-11e6-846a-fa9fab33c538.PNG)

**Comment by AlbinoDrought** [comment]
I'm not sure how proper of a "fix" this is, but it is working.

There are two instances of the following in the code:

         // Reset internal input's size
         var textLength = $input.val().length,
            wordSpace = Math.ceil(textLength / 5),
            size = textLength + wordSpace + 1;
         $input.attr('size', Math.max(this.inputSize, $input.val().length));

It generates a nice size variable for us, but then proceeds to use the length of the input text. I changed both of these to the following:

        // Reset internal input's size
        var textLength = $input.val().length,
            wordSpace = Math.ceil(textLength / 5),
            size = textLength + wordSpace + 1;
        $input.attr('size', Math.max(this.inputSize, size));

Now the input element properly resizes (for me, at least)

**Comment by cr1t** [comment]
I resolved this by disabling the hint, thank for the repply
