### ISSUE TITLE
minChars

### ISSUE THREAD

**Issue by federicolucca** [bootstrap-tagsinput/bootstrap-tagsinput#510]
hi everyone,

There is a minChars options ?

Thanks
Federico

**Comment by rswhite7** [comment]
@federicolucca there isn't but I used the `beforeItemAdd` event to disallow any tag with less than 3 characters:

    $('#tagsInput').on('beforeItemAdd', function(event) {
        if (event.item.length < 3) {
            event.cancel = true;
        }
    });

**Comment by HagarMohammed7** [comment]
@rswhite7 where is put it in code

**Comment by HagerMohammed** [comment]
@rswhite7  where is to put it ?
