### ISSUE TITLE
How to allow only values from source as tags

### ISSUE THREAD

**Issue by cmanish049** [bootstrap-tagsinput/bootstrap-tagsinput#512]
Is there a way to allow only values returned from source as tags to be input.

**Comment by ideasvn** [comment]
I want too. Please update example about it. Thank you!

**Comment by raknjak** [comment]
This is a very important request because most people would probably like to limit input to their data set.
cheers

**Comment by wwwjsw** [comment]
```
$('#element').tagsinput({
  freeInput: false
});
```

**Comment by laiwenqiang** [comment]
$('#element').tagsinput({
  freeInput: false
});
