### ISSUE TITLE
Tag exceeding out of input limit.

### ISSUE THREAD

**Issue by rchiranjeevi** [bootstrap-tagsinput/bootstrap-tagsinput#514]
Below is an image of UI 
![screenshot from 2016-08-02 12 49 38]
(https://cloud.githubusercontent.com/assets/16027378/17320196/e3d7b26a-58af-11e6-906a-dfc79e242904.png)

**Comment by rodrigovallades** [comment]
+1

If you paste the text, it exceeds the maxchars limit.

**Comment by lucknerjb** [comment]
Will be resolved in #523. Closing dupe
