### ISSUE TITLE
Autosuggest by Listing Down

### ISSUE THREAD

**Issue by tetrahydra** [bootstrap-tagsinput/bootstrap-tagsinput#517]
Hello,

I have preloaded values of "popular tags".
1. Instead of typing down the first character, I would like to suggest available tags on focus.
2. Chosen tags should not be shown for duplicate.

How can I achieve this?

Thank you.

**Comment by lucknerjb** [comment]
If you look at the typeahead documentation, there are examples on how to show the values on focus (without needing to type anything)
