### ISSUE TITLE
Initialization not taking default overrides

### ISSUE THREAD

**Issue by polomint82** [bootstrap-tagsinput/bootstrap-tagsinput#521]
I have an issue where the defaults are only working if I leave $('input') as the taginput control versus specifying the id of the input. Obviously using 'input' won't work since that updates all inputs on the page. My code is simply:

var elt = $('#tagControl');
        elt.tagsinput({
            onTagExists: function (item, $tag) {
                alert()
                $tag.hide().fadeIn();
            },
            freeInput: true
        });

The alert is never hit above. I thought it might be that I was adding inputs in the ajax call, but it doesn't seem to matter all:

```
    $.ajax({
        type: "POST",
        async: false,
        contentType: "application/json; charset=utf-8",
        url: "REMOVED_URL",
        data: "{arg: 1, arg2: 2}",
        dataType: "json",
        success: function (response) {
            var result = JSON.parse(response.d);
            if (null !== result) {
                $.each(result, function (index, itemData) {
                    hashtable[itemData.TagValue] = itemData.TagId;
                    $('#tagControl').tagsinput('add', itemData.TagValue);
                });
            }
        },
        error: function (response) {
            console.log(response);
        }
    });
```

Any help would be appreciated since I've just about had it and I don't really want to pull the page out again.

thanks,
Andrew

**Comment by GrgDmr** [comment]
I had the same problem .

Looking at the code I found that the library automatically searches the page any controls that meet this filter :

`  Initialize tagsinput behaviour on inputs and selects which have data-role=tagsinput

$(function() {
     $("input [data-role=tagsinput ] , select [multiple] [data-role=tagsinput ]".tagsinput ( ) ;
});`
line 725 of bootstrap-tagsinput.js file

This causes an override of custom initialization .

To operate my initialization is enough to remove from controls of type " tag input" the attribute "data- role = tagsinput ".

**Comment by lucknerjb** [comment]
Hey guys, thanks for pointing this out.

@GrgDmr, one option would be to just use the config if there is one set **OR** allow the use of more attrs like `data-tagsinput-max-tags`. What are your thoughts?
