### ISSUE TITLE
Typeahead does not clear

### ISSUE THREAD

**Issue by cr1t** [bootstrap-tagsinput/bootstrap-tagsinput#522]
Hi have this typeahead issue that is not clearing the input value.

Things to know:
1. Very hard to reproduce
It does not happen all the time it takes some playing around doing the same actions over and over before it happen.
2. Steps to reproduce
Start typing use the down arrow to select the and press enter.
Or start typing and use the mouse to select item.
3. Not all browsers.
And when I say not all browsers I mean only Edge does not show the same issue
4. Values do clear sometimes
Sometimes just clicking some place else will clear the values.

![typeaheadbug](https://cloud.githubusercontent.com/assets/4394765/18119055/ef27e918-6f58-11e6-8ed1-a8ea96996303.gif)

**Comment by nwoetzel** [comment]
Could be a dublicate of #331

**Comment by cr1t** [comment]
I had a look most of those suggestion I see have made it to the version I have.

**Comment by lucknerjb** [comment]
@cr1t Sorry for the late reply. Are you still seeing this as an issue? I feel like I've seen it recently but I can't recall 100%. I'll add the proper labels for now and plan to look into this

**Comment by cr1t** [comment]
Hi, yes we still have not resolved it. like i said it does not happen a lot
so we've not experienced a lot of complaints about it.
But is something I'd like to tick off my list of things to fix :)

**Comment by ieglonew01f** [comment]
I am consistently able to reproduce this on my mac/chrome browser. Can we please prioritize this.

**Comment by TheNewFM** [comment]
I ran into this issue while using Bootstrap-3-Typeahead. It seems to add a value to the input element after bootstrap-tagsinput clears it. I came up with the following workaround:

```javascript
$(selector).tagsinput({
  typeahead: {
    source: data,
    afterSelect: () => {
      $(selector).tagsinput('input').val('');
    }
  }
});
```

**Comment by petermorlion** [comment]
@TheNewFM unfortunately, that won't work on Bootstrap 2. (I know we should upgrade, but, you know, company priorities and that). And as this library also supports Bootstrap 2, I looked for another solution. Also, it allows the bootstrap-tagsinput to solve it, instead of having to do it yourself.
It's based on comments I found [here](https://github.com/twitter/typeahead.js/issues/233):

    if ($('.typeahead, .twitter-typeahead', self.$container).length) {
        setTimeout(function () { self.$input.val(''); }, 0);
    }

I created a [pull request](https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/pull/566) for this.

**Comment by fahadali916** [comment]
I tried it like this and it worked

$(selector).tagsinput({
  typeahead: {
    source: data,
    afterSelect: () => {
      $('.bootstrap-tagsinput input').val('');
    }
  }
});

The "bootstrap-tagsinput" is the div container created by bootstrap-tagsinput.
