### ISSUE TITLE
couldn't work on bootstrap modal

### ISSUE THREAD

**Issue by Dwiga** [bootstrap-tagsinput/bootstrap-tagsinput#524]
when I want to use it tags input on my modal, it wouldn't appear. just bootstrap form control same still...
thank for your help..

**Comment by lucknerjb** [comment]
Can you provide a jsfiddle example? Is your modal's content already loaded on the page when you initialize tagsinput? If not, you need to initialize tagsinput *after* you open the modal

**Comment by harrisonhm** [comment]
Whenever you load a new tags input field into the page, there should be the accompanying javascript:

// Destroy all previous bootstrap tags inputs (optional)
$('input[data-role="tagsinput"]').tagsinput('destroy');
// Create the bootstrap tag input UI
$('input[data-role="tagsinput"]').tagsinput('items');

**Comment by japita-se** [comment]
Same here, in modal not work correctly.

<div class="modal-body" style="display:inline-block;padding-bottom:40px">
                <div id="<?php echo $messageAreaId; ?>">
                    
                    <div class="col-xs-12">
                       
                    </div>
                    <div  class="col-xs-12">
                        <div id="bag_counter" class="">
                        
                        </div>
                        <input   multiple data-role="tagsinput" type="text" >
                        
                    </div>
                    
                </div>
            </div>

**Comment by pablocorezzola** [comment]
All work in perfect harmony. 
https://jsfiddle.net/piojoman/ywdnc7q3/1/

Try to move jquery, bootstrap and inputtags file (script tags - .js) on top to page...

**Comment by Dwiga** [comment]
i've fix it then,, thank you all
