### ISSUE TITLE
calling .tagsinput('items') inside an beforeItemAdd event handler causes a lot recursion

### ISSUE THREAD

**Issue by jkhsjdhjs** [bootstrap-tagsinput/bootstrap-tagsinput#528]
Let's say you have a usual tagsinput form and you attach an `beforeItemAdd` event handler to it, in that event handler you then use `$(this).tagsinput('items')` in any way. You should now have something like this:

``` javascript
$('your tagsinput').on('beforeItemAdd', function() {
    console.log($(this).tagsinput('items'));
});
```

Then you load the page where the tagsinput is located.
It will cause high CPU usage for your browser and firebug showed 'too much recursion'
It will also duplicate your tagsinput form about 300 times.

**Comment by belst** [comment]
example fiddle:

https://jsfiddle.net/ppxztk3m/

**Comment by lucknerjb** [comment]
After spending a little bit of time looking into this, the issue comes from not wrapping that chunk of JS in a `document.ready` function. I'm still not exactly 100% sure why not doing so causes an issue but that's the cause.

**Comment by belst** [comment]
In our usecase the script gets loaded AFTER the DOM has already finished. so there shouldnt be a need to wait for dom ready since it already is.

it is also like this in the fiddle:
https://jsfiddle.net/ppxztk3m/2/
