### ISSUE TITLE
Using Capybara to run Feature Spec? Capybara::ElementNotFound Error

### ISSUE THREAD

**Issue by harrisonhm** [bootstrap-tagsinput/bootstrap-tagsinput#529]
Trying to run Capybara with Selenium in a feature spec to inputting data into this.

Here's the Scenario:

`scenario "Adding a new post with valid attributes" do
        visit "/"

```
    click_link "New Post"

    fill_in "Title", with: "This is a Post Title"
    fill_in "Body", with: "This is a Post Body"
    fill_in "Tag list", with: "These, are, post, tags"

    click_button "Create Post"

    expect(page).to have_content("This is a Post Title | My Name")
end`
```

Here's the element as it appears in the browser:

`<div class="field">
  <label for="post_tag_list">Tag list</label><br>
  <input data-role="tagsinput" class="form-control" type="text" value="" name="post[tag_list]" id="post_tag_list" style="display: none;"><div class="bootstrap-tagsinput"><input type="text" placeholder="" style="width: 3em !important;"></div>
  </div>`

It just seems a bit odd because besides the data-role attribute it's not really any different than a normal textfield. I don't understand why Capybara can't find it.

**Comment by lucknerjb** [comment]
Are you sure Capybara is not filling in the hidden field? I'm not sure if
it makes the distinction between "fill in the first field" vs "fill in the
first visible field" as either option is a valid one in a test case.

I don't remember much about Capybara but have you tried passing in a
selector query for the visible input? If Capybara accepts those, I imagine
that would work.

If not, this is more a question for the Capybara project and not bootstrap
tagsinput.

**Comment by harrisonhm** [comment]
Yeah, the finders can't see it either. Like I said, the issue is that Capybara can't see the field, let alone try and fill it in. I'll leave it open in case some kind soul runs in to a similar issue and finds the answer.
