### ISSUE TITLE
.tt-cursor format missing in bootstrap-tagsinput-typeahead.css

### ISSUE THREAD

**Issue by mgbckr** [bootstrap-tagsinput/bootstrap-tagsinput#531]
Hi, I have noticed that when using typeahead.js, the suggestion is not highlighted when selecting by mouse-up and mouse-down. These selections are indicated by the `.tt-cursor` class, which is added to the respective `div` when it is selected. In the `bootstrap-tagsinput-typeahead.css` you can find this entry: 

```
.tt-suggestion:hover,
.tt-suggestion:focus {
    color: #ffffff;
    text-decoration: none;
    outline: 0;
    background-color: #428bca;
}
```

Thus, in order to enable suggestion highlighting, I would suggest changing it to:

```
.tt-suggestion:hover,
.tt-suggestion:focus,
.tt-cursor {
    color: #ffffff;
    text-decoration: none;
    outline: 0;
    background-color: #428bca;
}
```

**Comment by anoc** [comment]
This definetly needs to be pulled.
Otherwise there is no highlight when moving up and down with arrow keys. 
TY!
