### ISSUE TITLE
text input not auto width when past to input

### ISSUE THREAD

**Issue by chettapong** [bootstrap-tagsinput/bootstrap-tagsinput#538]
when past data to input, input can't auto width fit data
it try add code it can work

`self.$container.on('paste', 'input', $.proxy(function (event) {
          var $input = $(event.target);
          setTimeout(function () {
              var textLength = $input.val().length,
                 wordSpace = Math.ceil(textLength / 5),
                 size = textLength + wordSpace + 1;
              $input.attr('size', Math.max(this.inputSize, $input.val().length));
          }, 100);
      }, self));`

**Comment by japita-se** [comment]
Same here. If I start typing in the input, the width changes.
The tagsinput is inside a bootstrap modal.

```
<div class="modal-body" style="display:inline-block;padding-bottom:40px">
                <div id="<?php echo $messageAreaId; ?>">
                    
                    <div class="col-xs-12">
                       
                    </div>
                    <div  class="col-xs-12">
                        <div id="bag_counter" class="">
                        
                        </div>
                        <input   multiple data-role="tagsinput" type="text" >
                        
                    </div>
                    
                </div>
            </div>
```

**Comment by huma-hamid** [comment]
It would be nice to have a fix for this open issue, but solution provided by chettapong works perfectly! Thank you chettapong!

**Comment by ManuelPereira2016** [comment]
> when past data to input, input can't auto width fit data
> it try add code it can work
> 
> `self.$container.on('paste', 'input', $.proxy(function (event) { var $input = $(event.target); setTimeout(function () { var textLength = $input.val().length, wordSpace = Math.ceil(textLength / 5), size = textLength + wordSpace + 1; $input.attr('size', Math.max(this.inputSize, $input.val().length)); }, 100); }, self));`

Sorry but didn't see why are you creating those local variables inside setTimeout if you are not using them.

**Comment by chettapong** [comment]
> 
> 
> > when past data to input, input can't auto width fit data
> > it try add code it can work
> > `self.$container.on('paste', 'input', $.proxy(function (event) { var $input = $(event.target); setTimeout(function () { var textLength = $input.val().length, wordSpace = Math.ceil(textLength / 5), size = textLength + wordSpace + 1; $input.attr('size', Math.max(this.inputSize, $input.val().length)); }, 100); }, self));`
> 
> Sorry but didn't see why are you creating those local variables inside setTimeout if you are not using they.

Sorry I did not code well.
At that time, I wrote JavaScript not well understood. But now I understand the declaration of those variables.
