### ISSUE TITLE
Always full width

### ISSUE THREAD

**Issue by ghost** [bootstrap-tagsinput/bootstrap-tagsinput#545]
Hello,
I am using tagsinput in RTL (Right to left) environment.
Now I the input is half width look like image:
![untitled](https://cloud.githubusercontent.com/assets/1716006/20608559/3109a83a-b298-11e6-9970-78d11e2c19f6.jpg)

How can I fix it?

**Comment by pablocorezzola** [comment]
Hi, try it and see how you get along

`
.bootstrap-tagsinput .tag {
		float: right;
		margin-top: 3px;
	}`

	.bootstrap-tagsinput > input {
		float: right !important;
		text-align: right;
	}

https://jsfiddle.net/piojoman/x08zcdqk/1/

**Comment by pablocorezzola** [comment]
Hi, try it and see how you get along

`div.bootstrap-tagsinput{float:right; width:100%}`

It can assist in developing 

`
.bootstrap-tagsinput .tag {
		float: right;
		margin-top: 3px;
	}`

	.bootstrap-tagsinput > input {
		float: right !important;
		text-align: right;
	}

https://jsfiddle.net/piojoman/x08zcdqk/1/

**Comment by haulpd** [comment]
you can use attribute data-width = "100%".
