### ISSUE TITLE
Drop a newline using typehead

### ISSUE THREAD

**Issue by dzpt** [bootstrap-tagsinput/bootstrap-tagsinput#546]
I see the different in `.twitter-typeahead` style in the demo vs latest version.
using `display:inline-block` with drop a newline like image below.
Tested on both chrome , firefox on Mac

![screen shot 2016-11-25 at 2 44 19 pm](https://cloud.githubusercontent.com/assets/5781080/20617725/af40cb18-b31d-11e6-9212-7f5b5604e5f8.png)

Changed to use `display:inline` kills this error but the suggestion display on the wrong position for the first tag (the second one is ok!)
![screen shot 2016-11-25 at 2 47 02 pm](https://cloud.githubusercontent.com/assets/5781080/20617861/68178dc0-b31e-11e6-9a3f-7db3a3c9b5a8.png)

**Comment by patrickwai** [comment]
I meet the same problem,

**Comment by patrickwai** [comment]
the <span> element  when changing `display:inline-block`  --> `inline`, the problem disappeared.
