### ISSUE TITLE
How to restrict confirm keys to semicolon only.

### ISSUE THREAD

**Issue by subhanahmed047** [bootstrap-tagsinput/bootstrap-tagsinput#547]
Is there any way i can restrict the confirm keys to semicolon only? No matter what i change for ```confirmKeys: [13, 44]``` The default once's (comma, enter) still work. Can i disable the default one's? 

Any help would be appreciated.

**Comment by wwwjsw** [comment]
+1

**Comment by pablocorezzola** [comment]
It works

`			$("input").tagsinput({
				confirmKeys:[]
			});`

https://fiddle.jshell.net/piojoman/cg5a9t10/

**Comment by gustawdaniel** [comment]
In this example (from [jsfiddle](https://jsfiddle.net/piojoman/tocongur/))

It works when I typing "a b c", and "a, b, c". It is ok.
But when I pasting copied text: "a b c" a obtaining "a b c" as single item.
When I pasting "a, b, c" then string is divided properly.

Is there any manner to handle properly situation of pasting text with spaces?
