### ISSUE TITLE
Get Source from other text input field.

### ISSUE THREAD

**Issue by sergyyT** [bootstrap-tagsinput/bootstrap-tagsinput#549]
It possible with this plugin to get source for tags from other text input field.  Fox example user put/print in  "description"  form field, after it  text from this field to used like source for next form input "key word".  Accept Ajax call is any other way?

**Comment by pablocorezzola** [comment]
Maybe I can help you.

Here is an example.
https://jsfiddle.net/piojoman/vkyyzegm/1/
