### ISSUE TITLE
Characters cut off in input box in chrome

### ISSUE THREAD

**Issue by mstruensee** [bootstrap-tagsinput/bootstrap-tagsinput#550]
Chrome Version 54.0.2840.98 (64-bit)
![1212160826](https://cloud.githubusercontent.com/assets/5142984/21102756/18ee892c-c045-11e6-9be0-b62febd934fc.jpg)
![1212160826a](https://cloud.githubusercontent.com/assets/5142984/21102754/18ed5b6a-c045-11e6-8fbf-8240b7269f1e.jpg)
![1212160826b](https://cloud.githubusercontent.com/assets/5142984/21102755/18edf7be-c045-11e6-9dd7-f81bf677e2ae.jpg)

**Comment by zhouzihanntu** [comment]
Hey,  I've reached the same problem as yours, just fixed it with minor modification, since the PR was not merged by now, you can refer to the link address. [fixed text display problem](https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/pull/539) :  )

**Comment by mstruensee** [comment]
Thanks!

**Comment by zhouzihanntu** [comment]
sorry I'm not clear about that, seems the repository is not actively maintained at present.
