### ISSUE TITLE
itemValue returning another value

### ISSUE THREAD

**Issue by virtginia** [bootstrap-tagsinput/bootstrap-tagsinput#552]
Hello!

I have this jSon:
[{ "value" : "13", "text" : "fdg" },{ "value" : "12", "text" : "fdg" },{ "value" : "11", "text" : "fdg" },{ "value" : "10", "text" : "dsf" },{ "value" : "9", "text" : "testing" },{ "value" : "8", "text" : "test" },{ "value" : "7", "text" : "fdg" }]

And the input field is:
<input type="text" name="productos" id="productos" class="form-control" /> 

And my js code is:

var cities = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  prefetch: 'url_to_json'
});
cities.initialize();

elt = $('#productos');
elt.tagsinput({
  itemValue: 'value',
  itemText: 'text',
  typeaheadjs: {
    name: 'productos',
    displayKey: 'text',
    source: cities.ttAdapter(),
  }
});

But when is select, for example, the text "testing", instead of returning me the value 9 (when i get the input val() ) it returns me the value 5. The same happens to me when select another items. I can't find the problem in my code. What is this returning?

Thanks,
Virginia

**Comment by virtginia** [comment]
I think it's important to remark tha if I change the value of itemValue for another (also in jSon data) it doesn't work. I had to keep value name as itemValue.

**Comment by pablocorezzola** [comment]
Maybe I can help you.

use itemText property....

Here is an example.
https://jsfiddle.net/piojoman/0f7wro1u/2/

**Comment by virtginia** [comment]
Thanks a lot! I´ve already made it in a custom way but I´ll try this next time I´ll need it.  Best! Virginia
