### ISSUE TITLE
<fieldset disabled> support

### ISSUE THREAD

**Issue by HartLarsson** [bootstrap-tagsinput/bootstrap-tagsinput#554]
Is possible to disable the tags input like other form element if the **fieldset is disabled**?
actually if i disable the fieldset all other form fields are disabled but user can remove the tag

![image](https://cloud.githubusercontent.com/assets/16102074/21455003/48ef6d22-c91d-11e6-8b05-50f28264a2d7.png)

**Comment by pablocorezzola** [comment]
Try with css.

`.bootstrap-tagsinput input{
  visibility:hidden !important;
}`
`
.bootstrap-tagsinput > span > span{
  display:none !important;
}`

look at my sample... https://jsfiddle.net/piojoman/7a5xdvk5/

**Comment by HartLarsson** [comment]
yes is what I actually do too.
I think anyway that if the Tag field is inside a disabled fieldset the behaviour must be automatically applied instead to manually apply a CSS trick :)
