### ISSUE TITLE
typeahead not working

### ISSUE THREAD

**Issue by SushantRT** [bootstrap-tagsinput/bootstrap-tagsinput#555]
I'm using typeahead.js from http://twitter.github.io/typeahead.js/

My code is like below:

`
     
    <head>
        <link rel="stylesheet" href="http://getbootstrap.com/dist/css/bootstrap.min.css" />
    
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

        
        <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>

            
        <script src="Scripts/typeahead.js"></script>
        <link rel="stylesheet" href="CSS/typehead.css" />
        <script src="Scripts/bootstrap-tagsinput.js"></script>
    
    </head>
    <body>

        <input id="stateselect" type="text" data-role="tagsinput" />

    <script type="text/javascript">
       
        $(document).ready(function () {
            $("#stateselect").tagsinput({
                typeahead: {
                    source: ['abc','dfg','jkhdk','uihfasdhj']
                },
                freeInput: false
            });
        });

    </script>
    </body>
`

This code is not working. Am I missing something?

**Comment by kaytrance** [comment]
Should be (notice typeaheadjs instead of typeahead)
````
    $(document).ready(function () {
        $("#stateselect").tagsinput({
            typeaheadjs: {
                source: ['abc','dfg','jkhdk','uihfasdhj']
            },
            freeInput: false
        });
    });
````

**Comment by SushantRT** [comment]
Sorry, but as I can see here(official documentation): http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/  they have used typeahead.

Also using typeaheadjs didn't worked.

**Comment by amnesia7** [comment]
Is `typeahead` not for when using BS v2 whereas `typeaheadjs` for BS v3?

See code in http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/assets/app_bs3.js that uses `typeaheadjs`

**Comment by xuhuimale** [comment]
Facing the same problem.
Waiting for an answer...

**Comment by iftekharulislam** [comment]
The source property does not accept a simple array I think. It is accepting a some array from a BloodHound object. It worked for me. So you should try

```
var suggestions = ['tag 1', 'tag 2'];
var bloodHoundObj = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.whitespace,
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  // url points to a json file that contains an array of country names, see
  // https://github.com/twitter/typeahead.js/blob/gh-pages/data/countries.json
  local: suggestions
});
bloodHoundObj.initialize();

$timeout(function () {
  $('#page-tags').tagsinput({
    typeaheadjs: {
      source: bloodHoundObj.ttAdapter()
    }
  });
}, 1000);
```

**Comment by clenk** [comment]
Documentation on the examples page should be updated to reflect this.

**Comment by amnesia7** [comment]
@SushantRT if I add data attributes, eg `data-role="tagsinput"` to my input text field it doesn't seem to work properly. 

With `data-role="tagsinput"` the remote lookup fails and it no longer seems to call my remote url. If I remove the `data-role` attribute it starts working again...weird.

Also, if I add `data-tagsinput="true"` it stops working completely and no longer works as a tagsinput field at all.

Anybody got any ideas or can confirm if this is the case for them also?

Col

**Comment by amnesia7** [comment]
I was hoping to make my code more generic (using data attributes) for applying tagsinput but if it fails when the input field has data attributes that really does prevent the idea.

**Comment by amnesia7** [comment]
Having looked at the code, I think I see the issue.

`$(this).data('tagsinput', tagsinput);` will be why my data-tagsinput="true" stopped it working completely because my data attribute was getting confused with the one applied by the plugin.

Also, `$("input[data-role=tagsinput], select[multiple][data-role=tagsinput]").tagsinput();` will be why when using `data-role="tagsinput"` remote doesn't work; because it probably applies a basic tagsinput setup whereas to use remote etc (i.e. more complex setup) then you need to use custom code (blookdhound adapter etc) to apply tagsinput to the input text field.

**Comment by lvpro** [comment]
I agree, the code on the examples page does NOT work.  Setting source: to an array, or a function which returns a simple array does not work.  However, you can do it the "typeahead" way wherein the second parameter is the sync callback, and it works ... (though, to add to the frustration, using the 3rd parameter for async data per typeahead does NOT work).

source: function(q, sync) {
   sync(['My', 'Typeahead', 'Values']);
}

**Comment by mekalasuraj** [comment]
I am having trouble integrating bootstrap 3 typeahead with tags input but 
    with objects as tags. It works if I use only tagsinput on input field, but 
    if I integrate it with typeahead then it doesn't work and I don't even get 
    any errors 
   
   // In my jsFile
       These are the modules i am using
       require('bootstrap-3-typeahead/bootstrap3-typeahead.min.js');
       require('bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js');
       require('bootstrap-tagsinput/dist/bootstrap-tagsinput.css');      
    //function for Typeahead
       $('#text').tagsinput({
       typeahead: {
       source: ['Alabama','Alaska','Arizona','Arkansas','California']
       }});
    //In HTML File
       <input type="text" class="form-control" name="test" 
       id="test" data-role="tagsinput" />

**Comment by vcdep-xp** [comment]
Hi everybody!

I had same problem with integration, my solution was:

1) IMPORTANT: In the input where you want to inplement 'tagsinput' don't add data-role="tagsinput"

2) Init script:
<script type="text/javascript">
  $(document).ready(function() {

    ///////////// Input tags ///
    $('#tags').tagsinput({
      typeahead: {
        source: <?=json_encode($dataTags)?>,
      },
    });///
    $('#tags').on('itemAdded', function(event) {
      // event.item: contains the item
      setTimeout(function() {
        $('.bootstrap-tagsinput :input').val(''); // Patch: In my case when selecting an option, the input (with typeahead) added the suggested text twice)
      }, 0);
    });
    ////////////////////////////

  });
</script>

I'm working with:
- Bootstrap Tags Input https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/
- Bootstrap 3 Typeahead https://github.com/bassjobsen/Bootstrap-3-Typeahead

**Comment by timeceeper** [comment]
Hi, does everyone have a solution for this?
I have made a fiddle. 
https://jsfiddle.net/32j9kyc5/

the suggestions does not appear,

**Comment by kshlyk** [comment]
$('input#tags').tagsinput({
    typeaheadjs: {
      name: 'my-dataset',
      source: function(query, syncResults){
        syncResults(['Amsterdam', 'Washington', 'Sydney', 'Beijing', 'Cairo']);
      }
    },
    cancelConfirmKeysOnEmpty: true, 
    freeInput: true
  });
