### ISSUE TITLE
count how many data that I have input

### ISSUE THREAD

**Issue by Dwiga** [bootstrap-tagsinput/bootstrap-tagsinput#559]
I want to asking here,
I have plan to input some data, but if i want to check it again it'll take some time to count.
the answer is, how to add counter how many data on bootstrap-tagsinput

**Comment by querubinRamonchito** [comment]
You can use the below statement (this is of course written in typescript but can be translated to an ordinary javascript code): 

var tagsInputTxt = $('#tagsInputId').tagsinput('items');
var tagsInputLength = tagsInputTxt.length;

Hope that helps.
