### ISSUE TITLE
Jquery validate / validate unobtrusive issue

### ISSUE THREAD

**Issue by Shaninnik** [bootstrap-tagsinput/bootstrap-tagsinput#563]
I am using tagsinput with typeahead inside form that also has other fields validated with Jquery validate unobtrusive. Tagsinput field is not required, and I am not setting any require options for it anywhere, but somehow when I try to submit the form it returns validation error on .tt-input field. Running `$( ".tt-input" ).rules()` returns `{required: true, __dummy__: true}` so require gets added somewhere automatically.  This does not happen with other inputs so it is defenitely connected with Tagsinput.

As a workaround I was able to call `$( ".tt-input" ).rules("remove", "required")` to remove the require rule manually, it works but took me some time to figure it out. Would be nice to know why it gets added though.

**Comment by NirmalAnandKuzhandaivel** [comment]
Even i am facing same issue. When i use tagsinput for a textbox in html . the jquery validator does not run.
