### ISSUE TITLE
allowDuplicates is true ,After deleting a value error

### ISSUE THREAD

**Issue by jl945** [bootstrap-tagsinput/bootstrap-tagsinput#588]
1,1,1,1  delete 1 ,Value should be 1,1,1，but is null

**Comment by PusitK** [comment]
I have a same problem. Do u have anu solution to solve this issue? thank anyway.

**Comment by david43** [comment]
update bootstrap-tagsinput.js remove function
line 203 
`$('.tag', self.$container).filter(function() { console.log($(this).data('item'));return $(this).data('item') === item; }).remove();`
to 
`
$('.tag', self.$container).each(function(){
			if($(this).data('item') === item)
			{
				$(this).remove();
				return false;
			}
		});`
