### ISSUE TITLE
Adding tag in bootstrap tags input dynamically not working

### ISSUE THREAD

**Issue by malik-umair** [bootstrap-tagsinput/bootstrap-tagsinput#592]
I'm trying to set tags via bootstrap tags input but it's not working and giving following error:

    TypeError: b.options.itemValue(...) is undefined

my code is as follow:

    $('#searchGeoBottom').tagsinput({
    maxTags: 5,
    delay: 500,
    itemValue: 'value',
    itemText: 'text',
    typeahead: {
        displayKey: 'text',
        source: function (query) {
            if (ajax) {
                ajax.abort();
            }
            var data = {term: query};
            ajax = $.getJSON((baseUrl + "geoSearch"), data);
            return ajax;
        },
        afterSelect: function () {
            this.$element[0].value = '';
        }
    }
    });
    if (typeof searchGeo != 'undefined' && searchGeo != '') {
      $('#searchGeoBottom').tagsinput('add', searchGeo);
    }

I've also tried following approach which i found while searching:

    var elt = $('#searchGeoBottom').tagsinput({....});
    elt.tagsinput('add', searchGeo);

But it didn't work either, gives elt is not defined or elt is not a function..

Following is the json I'm passing in add function:

    [{"text":"Lahore. United States","value":4768156}]

**Comment by ReDraft** [comment]
Hi sorry for my Bad English at first.

For you and all others hwo love this plugin and wouldn't to do without it, here my Solution:

You must use the code from this pull request [here](https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/pull/583/commits/503b422ce83b26cf7513e4e45039e8f8b7a26307) ant then you must also change two line in the code for working a little bit easier:

- first Line on 46 from `this.objectItems = options && options.itemValue;` to `this.objectItems = options && options.itemText;`

- second line on 270 from `return self.options.itemValue(item).toString();` to `return self.options.itemText(item).toString();`


I build actually an new Laravel 5.4 App with Twitter Bootstrap 4 alpha-6 and it works like a charm after 2 Days searching an without Sleep ;)

_by the way as short explanation:_
New Tags in Database havn't an Id, i must at first after freeType only displax the label and this ist stored in itemText :))

Have Fun and i hope it helps you

**Comment by Kuari** [comment]
I have the same error.But i can add the tag only once.My code as follow:
`function test(obj){
var $id = document.getElementById(obj.id);
var elt = $('#tags');
elt.tagsinput({
  itemValue: 'value',
  itemText: 'text',
});


if ($id.checked)
{
elt.tagsinput('add', {"text": $id.value});
}
else
{
elt.tagsinput('remove', {"text": $id.value});
}
}
`
