### ISSUE TITLE
tagsinput + typeheadjs

### ISSUE THREAD

**Issue by AydarAkhmetzyanov** [bootstrap-tagsinput/bootstrap-tagsinput#595]
In the example page when you enter something in the input field with typehead and press somewhere else on the page, input field loses focus but input value does not automatically converts to tag. But it works in general example without typehead.

**Comment by mgralikowski** [comment]
Here:
https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/509
workaround.
