### ISSUE TITLE
Wrong values and behavior when remove item when enable allowDuplicates

### ISSUE THREAD

**Issue by Gnoc** [bootstrap-tagsinput/bootstrap-tagsinput#598]
When I allow for duplicates value on input. After added 3 same items.
![image](https://user-images.githubusercontent.com/10009897/27680454-f8cfddf6-5ce5-11e7-839d-d1db31181fa9.png)

And after remove 1 item, the input will auto hide all same item. But input.val() is still have hidden items
![image](https://user-images.githubusercontent.com/10009897/27680471-07243f96-5ce6-11e7-8e1b-40cdf3a9db3a.png)

**Comment by alansolis** [comment]
I have the same issue. Duplicate the values.


![tags](https://user-images.githubusercontent.com/6597919/27690398-ded083a4-5ca6-11e7-80c8-b63c84b3181c.JPG)

**Comment by ronnieguha** [comment]
Same issue here.. anyone found a fix yet?

**Comment by ChwingWong** [comment]
Because the remove function is handled this way
`$('.tag', self.$container).filter(function() {
                    return $(this).data('item') === item;
                }).remove();`
