### ISSUE TITLE
add method not working

### ISSUE THREAD

**Issue by balabp** [bootstrap-tagsinput/bootstrap-tagsinput#602]
add/remove method when using javascript to add tags is not working. It creates a new input tag every time
![image](https://user-images.githubusercontent.com/8764294/27976902-0f9aaf0e-632e-11e7-87f3-b13e612786a1.png)

**Comment by macwac** [comment]
did you have any error in console?

**Comment by balabp** [comment]
below is the error - 
<img width="931" alt="screen shot 2017-07-09 at 1 46 40 pm" src="https://user-images.githubusercontent.com/8764294/27996679-21af80b8-64ad-11e7-9ae0-871ee06ee6c6.png">

**Comment by macwac** [comment]
ok first try to define taginputs field like:
```javascript
elt = $('.example_objects_as_tags > > input');
elt.tagsinput({
  itemValue: 'value',
  itemText: 'text',
});
```
and now try something like this
```javascript
elt.tagsinput('add', { "value": 1 , "text": "Amsterdam" });
```
