### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by SamuelToh** [bootstrap-tagsinput/bootstrap-tagsinput#603]
Hi, I'm trying to use this plugin for an angular project but I couldn't figure out what is needed.

Based on the example found [here](https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/blob/master/examples/index.html#L294).

I had imported the mentioned `bootstrap-tagsinput-angular.js` and injected `bootstrap-tagsinput` as the dependency.
I got this error "TypeError: select.tagsinput is not a function".
[screenshot](https://drive.google.com/open?id=0B_A8Orva8UeDelRpdW1RX2p6NUk)

I thought it'll be nice if we can have an installation guide on what the command to run for downloading this package like `bower install blah --save` and which `css` | `js` files to import, and how to inject the dependency.

I think it will make this project a bit more user-frienedly.

**Comment by JD719** [comment]
I agree with you, I spent some time trying to make it work without any luck.
Couldn't say if I am doing something wrong or it is just broken as there is no install instructions.
