### ISSUE TITLE
Is anyone here who can merge or does someone want to fork?

### ISSUE THREAD

**Issue by johnmcconnell** [bootstrap-tagsinput/bootstrap-tagsinput#605]

**Comment by andrewpros** [comment]
Same question here, great project but it looks like abandoned, so many great fixes and options just wait to accept the PR, but looks like no one cares?

I think we need some clarification about the project status @lucknerjb , right?

Or just give someone that have time to support this project some access rights.

**Comment by hrobertson** [comment]
@danielsvane @tim-peterson ?

**Comment by jesperronn** [comment]
Is this project being maintained? I am also wondering why [the most recent release v0.8.0](https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/releases/tag/0.8.0) (18 months old) is not to be found on [npmjs.org](https://www.npmjs.com/package/bootstrap-tagsinput)

**Comment by hrobertson** [comment]
I did a bit of work to bring in other people's bug fixes and made changes of my own: https://github.com/hrobertson/bootstrap-tagsinput

But then I found this which just works for my needs: https://github.com/Open-Xchange-Frontend/bootstrap-tokenfield

**Comment by danielsvane** [comment]
I'm sorry I haven't replied to this sooner. For some reason, can't remember why, I have admin rights over this repo. I doubt it's still being maintained, but if you are interested in taking over, maybe I can do something about it.

**Comment by velegip** [comment]
@danielsvane 
Can you update the npm package?

**Comment by sunknudsen** [comment]
@danielsvane, I would love to help maintain this library. I don't have a lot of time at hand, but could add a little bandwidth to the team. Let me know.

**Comment by sunknudsen** [comment]
Hey guys, ended up trying [Selectize](https://selectize.github.io/selectize.js/). Pretty happy so far.

Btw, Selectize is also looking for new members on their maintenance team.
