### ISSUE TITLE
Typeahead Objects as tags initialisation

### ISSUE THREAD

**Issue by dams666** [bootstrap-tagsinput/bootstrap-tagsinput#609]
I use Typeahead with Objects as tag.

Is it possible to initialise the input default values by passing its id's  directly (coma separated) ? 
This would avoid having to parse cities.json to provide the name

```

var cities = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  prefetch: 'assets/cities.json'
});
cities.initialize();

var elt = $('input');
elt.tagsinput({
  itemValue: 'value',
  itemText: 'text',
  typeaheadjs: {
    name: 'cities',
    displayKey: 'text',
    source: cities.ttAdapter()
  }
});

elt.tagsinput('add', { "value": 1 , "text": "Amsterdam"   , "continent": "Europe"    });
elt.tagsinput('add', { "value": 4 , "text": "Washington"  , "continent": "America"   });
elt.tagsinput('add', { "value": 7 , "text": "Sydney"      , "continent": "Australia" });
elt.tagsinput('add', { "value": 10, "text": "Beijing"     , "continent": "Asia"      });
elt.tagsinput('add', { "value": 13, "text": "Cairo"       , "continent": "Africa"    });


```

**Comment by hrobertson** [comment]
I'm struggling to understand what you're trying to achieve.
What do you mean by "the input default values"?

Is this question specific to bootstrap-tagsinput or is it actually about [typeaheadjs](https://github.com/corejavascript/typeahead.js/blob/master/doc/jquery_typeahead.md) or [bloodhound](https://github.com/corejavascript/typeahead.js/blob/master/doc/bloodhound.md)?

If you could try re-wording and explaining the behaviour you're trying to achieve that could be helpful.
Thanks
