### ISSUE TITLE
Tags with comma

### ISSUE THREAD

**Issue by danndaghost** [bootstrap-tagsinput/bootstrap-tagsinput#610]
Hello, i wanna use the comma in tags. Change delimiter to ' | ' and when do submit still recive comma separator for input value. 
Add this lines to pushVal

var delimiter = (self.options.delimiterRegex) ? self.options.delimiterRegex : self.options.delimiter;
self.$element.val(val.join(delimiter)).trigger('change');

and works!

**Comment by Grunfi** [comment]
Thanks!

**Comment by filiperhiza** [comment]
Very nice, helped me a lot. Thank you

**Comment by leon0707** [comment]
Looks like no one maintains this repo anymore. This should be added into the source.

**Comment by ElsnerPHP** [comment]
Looks like no one maintains this repo anymore. This should be added into the source.

**Comment by Souvikray** [comment]
I am using version **0.8.0** but this solution still doesn't solve the problem. Here is the piece of code I changed in `bootstrap-tagsinput.js`

```
pushVal: function() {
      var self = this,
          val = $.map(self.items(), function(item) {
            return self.options.itemValue(item).toString();
          });

      //self.$element.val(val, true);   //commented this
      // my change
      var delimiter = (self.options.delimiterRegex) ? self.options.delimiterRegex : self.options.delimiter;
      self.$element.val(val.join(delimiter)).trigger('change');

      if (self.options.triggerChange)
        self.$element.trigger('change');
    },
```
Am I doing anything wrong?

**Comment by Souvikray** [comment]
Thanks! This worked for me. For those who want to know what exactly to do, I have posted the code below

```
pushVal: function() {
      var self = this,
          val = $.map(self.items(), function(item) {
            return self.options.itemValue(item).toString();
          });

     // commented this
      /*
      self.$element.val(val, true);
      if (self.options.triggerChange)
        self.$element.trigger('change');
      */

     // added this
     var delimiter = (self.options.delimiterRegex) ? self.options.delimiterRegex : self.options.delimiter;
     if (self.options.triggerChange)
        self.$element.val(val.join(delimiter)).trigger('change');

    },
```
