### ISSUE TITLE
Project or fork maintainers?

### ISSUE THREAD

**Issue by jesperronn** [bootstrap-tagsinput/bootstrap-tagsinput#613]
Is this project being maintained? 

I am wondering why [the most recent release v0.8.0](https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/releases/tag/0.8.0) (18 months old) is not to be found on [npmjs.org](https://www.npmjs.com/package/bootstrap-tagsinput)

**Comment by jesperronn** [comment]
Also, please comment if you know of other, maintained alternatives which can provide the same html

**Comment by mokoshalb** [comment]
You could try Tag-It http://github.com/aehlke/tag-it

**Comment by Nodws** [comment]
If you are looking for bootstrap4 compat
https://github.com/Nodws/bootstrap4-tagsinput

**Comment by gustawdaniel** [comment]
This project is not maintained.

In my opinion best alternative is add in packages.json dependency like this

    "bootstrap-tagsinput": "git+https://github.com/hrobertson/bootstrap-tagsinput.git",

This is fork but unfortunately not maintained too.
