### ISSUE TITLE
Can we change the close icon "x" on right hand side ?

### ISSUE THREAD

**Issue by hkbeer** [bootstrap-tagsinput/bootstrap-tagsinput#622]
Can we change the close icon "x" on right hand side ?
eg what if I want to change it to "+" ?

Which line of code I can change in js / css ?

**Comment by lijoev** [comment]
Yes it is possible to change
You can change the following section in bootstrap-tagsinput.css file
change this section 

`.bootstrap-tagsinput .tag [data-role="remove"]:after {
  content: "x";
  padding: 0px 2px;
}`
to
`.bootstrap-tagsinput .tag [data-role="remove"]:after {
  font-family: FontAwesome;
  content: "\f057";
  padding: 0px 0px;
  font-size: 12px;
  color:red;
}`
please see the image below
![tags](https://user-images.githubusercontent.com/19813885/39613991-cb9a91b8-4f89-11e8-83f4-8df40a85443d.png)
