### ISSUE TITLE
Version 0.8.0 is not available to install

### ISSUE THREAD

**Issue by JeyKeu** [bootstrap-tagsinput/bootstrap-tagsinput#624]
I go this error when I tried v `0.8.0`

`Couldn't find any versions for "bootstrap-tagsinput" that matches "^0.8.0"`

**Comment by dmarkin** [comment]
It needs to bump this version. So, until then only v0.7.1 is available from npm. See https://www.npmjs.com/package/bootstrap-tagsinput

**Comment by JeyKeu** [comment]
Docs need to be updated
