### ISSUE TITLE
Enter key submitting form, but can't make to be a confirm key

### ISSUE THREAD

**Issue by djmassive** [bootstrap-tagsinput/bootstrap-tagsinput#625]
I've try to use:

       `$(".tags").tagsinput({
		cancelConfirmKeysOnEmpty: true,
		confirmKeys: [13, 44]
	});`

But after I hit enter, whole form is submitting. I've try to block enter key on form with prevent - doesn't work too.

Another problem - after I use , as separator - its stays in field (screenshot)

<img width="498" alt="zrzut ekranu 2018-02-15 o 13 02 18" src="https://user-images.githubusercontent.com/1252451/36255744-83dd5a3e-1250-11e8-9c99-3a2f74f9f779.png">

**Comment by AgusRdz** [comment]
Hi @djmassive currently I have the same issue, I'm using this to solve for now

````
    $('.bootstrap-tagsinput input[type=text]').on('keydown', function (e)
        {
            if (e.which == 188) //188 = comma
            {
                $(this).blur();
                e.preventDefault();
                $(this).focus();
            }
        });
````

Regards

**Comment by scrawner** [comment]
Try this

`$('input[name=tags]').tagsinput();
                    $('.bootstrap-tagsinput input').keydown(function( event ) {
                      if ( event.which == 13 ) {
                        $(this).blur();
                        $(this).focus();
                        return false;
                      }
                    })`
