### ISSUE TITLE
Text goes beyond input when its length is exceeded

### ISSUE THREAD

**Issue by IhorDavydiuk** [bootstrap-tagsinput/bootstrap-tagsinput#633]
Hello! I noticed such a problem. When the text is exceeded in the input, the string goes beyond the input. The same happens when we make the screen size smaller.
![image](https://user-images.githubusercontent.com/30239457/38661777-a555e1fc-3e3a-11e8-9292-d5dfdf858c41.png)

**Comment by astijn3457** [comment]
Did you fix this already?
