### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by sadhnaprajapati** [bootstrap-tagsinput/bootstrap-tagsinput#635]
is there any way to add formula validation with error message.

**Comment by sunknudsen** [comment]
Hey @sadhnaprajapati,

Currently, I don’t believe there is.

That being said, validation should be pretty easy to implement using the `beforeItemAdd` event.

```
$('input').on('beforeItemAdd', function(event) {
  // event.item: contains the item
  // event.cancel: set to true to prevent the item getting added
});
```

Hope this helps!
