### ISSUE TITLE
div with class bootstrap-tagsinput generated twice causes a bad page view with typeahead

### ISSUE THREAD

**Issue by aleinnocenzi** [bootstrap-tagsinput/bootstrap-tagsinput#636]
I'm using bootstrap-tagsinput with typeahead with the following code:

`
    
    var tags = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        remote: {
            url: window.location.href + "&control=TagControl&method=LoadTags&query=%QUERY",
            wildcard: "%QUERY",
            filter: function (list) {
                return $.map(list, function (tagname) {
                    return { name: tagname };
                });
            },
            cache: false
        }
    });
    tags.initialize();

    $('.bootstrap-tagsinput input').tagsinput({
        typeaheadjs: {
            name: 'tags',
            displayKey: 'name',
            valueKey: 'name',
            source: tags.ttAdapter()
        }
    });`

The typeahead works correctly but if I inspect the html generated I see this:

![image](https://user-images.githubusercontent.com/16124682/39352224-62250f54-4a04-11e8-823b-1a8998d0627d.png)

As you can see the div with class bootstrap-tagsinput is generated twice and this causes a bad view in the page:

![image](https://user-images.githubusercontent.com/16124682/39352330-b41d34a8-4a04-11e8-9070-eb0cd4c31e95.png)

What am I doing wrong? Thanks.

EDIT: In the javascript I use tagsinput on $(".bootstrap-tagsinput input") selector because if I use only $("#inputTags"), where "inputTags" is the id of my input element, the typeahead doesn't work

**Comment by mantey-github** [comment]
@aleinnocenzi has your issue been solved. Facing the same issue

**Comment by alphadevx** [comment]
I have the same issue, have not found a workaround yet.

**Comment by jerrywilborn** [comment]
There is a double-initialization.  Anything with a data-role of 'tagsinput' will get constructed, then you are calling it a second time.  The solution is to remove the data-role since you are initializing it manually.
