### ISSUE TITLE
adding tags having issue in mobile browsers.

### ISSUE THREAD

**Issue by lijoev** [bootstrap-tagsinput/bootstrap-tagsinput#640]
We don't have an enter key in mobile browsers. so i am not able to add tags in mobile browsers. please help me to fix this issue.

**Comment by ee92** [comment]
Use a different key, such as space or comma.
`$('#input-id').tagsinput({
    confirmKeys: [13, 32, 44]
  })`
13 is enter, 32 is space, 44 is comma.
