### ISSUE TITLE
label class doesn't work for bootstrap 4

### ISSUE THREAD

**Issue by cfust** [bootstrap-tagsinput/bootstrap-tagsinput#645]
Using Bootstrap v4 and the `label label-info` classes don't work. I found the solution is just replace that with `badge badge-info`

**Comment by axis80** [comment]
Alternate, it's possible to define those styles by adding this to your CSS:

```
  .label {
      display: inline;
      padding: .2em .6em .3em;
      font-size: 75%;
      font-weight: 700;
      line-height: 1;
      color: #fff;
      text-align: center;
      white-space: nowrap;
      vertical-align: baseline;
      border-radius: .25em;
  }

  .label-info {
    background-color: #5bc0de;
  }

```

**Comment by rascii** [comment]
Go to the .JS file and search:
`label label-info`
and change it for
`badge badge-info`

**Comment by acdarekar** [comment]
https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/#options
The classname for tags can be updated as below:
`
$('input').tagsinput({
  tagClass: 'badge badge-info', \\ space-separated list of classes you want to add on each tag
  ...
});
`

**Comment by vachigaggl** [comment]
Did this over here:
https://github.com/vachigaggl/bootstrap-tagsinput, can create pull request if wanted.
