### ISSUE TITLE
Changing tagsinput properties after putting "data-role='tagsinput'"

### ISSUE THREAD

**Issue by tylorbayer** [bootstrap-tagsinput/bootstrap-tagsinput#646]
I would specify in your usage examples doc "http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/" that adding data-role='tagsinput' will create a default tagsinput of which the properties cannot then be modified. I spent quite a while trying to figure out why the allowDuplicates=true wasn't working. I finally guessed the issue is what I just described above. Once I got rid of the data-role='tagsinput' on my input element I was able to change the properties.

**Comment by btski** [comment]
The strange thing about this issue is it behaves differently for static html (breaks) vs dynamically programmed (no ill effect) input.
