### ISSUE TITLE
Repo activity?

### ISSUE THREAD

**Issue by jarrettj** [bootstrap-tagsinput/bootstrap-tagsinput#653]
Hi,

Good day.

Is this project still being maintained? There seems to be  XSS vulnerabilities. Thanks.

Regards.
Jarrett

**Comment by jlmakes** [comment]
![Waiting...](https://i.giphy.com/brHaCdJqCXijm.gif)

**Comment by gustawdaniel** [comment]
I solved by

```
    "bootstrap-tagsinput": "git+https://github.com/hrobertson/bootstrap-tagsinput.git",
```

in `package.json`. It see
