### ISSUE TITLE
How to append class or text to newly added tag?

### ISSUE THREAD

**Issue by tejashapani** [bootstrap-tagsinput/bootstrap-tagsinput#654]
Hello,

Is it possible to append something to newly added tag?

For example,
tag1 (50), tag2 (50) 
There are two existing tags and when i add another tag i.e. tag3, it will auto append '(50)' to tag3.

Thanks in advance

**Comment by pablocorezzola** [comment]
Please check it:
https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/pull/543

It's not official, but it can help
