### ISSUE TITLE
Show hint tags after type three characters

### ISSUE THREAD

**Issue by anoop-kiwi** [bootstrap-tagsinput/bootstrap-tagsinput#665]
Hello Team,

I want to show matching hint tags after type 3 characters in the input field. Please guide how I can achieve it.

Thanks in Advance.

Regards,
Anoop

**Comment by anoopyadav-kiwi** [comment]
Hello Team,

I'm waiting for your response.

**Comment by anoopyadav-kiwi** [comment]
Hello Team,

I'm using bootstrap-tagsinput v0.4.2.

**Comment by anoopyadav-kiwi** [comment]
Hello Team,

Is there any update on my request?
