### ISSUE TITLE
Support for Bootstrap 4

### ISSUE THREAD

**Issue by prakash03** [bootstrap-tagsinput/bootstrap-tagsinput#672]
I see a couple of relevant issues regarding support for Bootstrap 4 that were outdated. 

Just wanted to know if this repo currently supports Bootstrap4. I do not see any relevant commits specifying Bootstrap 4, and the readme still says it only support Bootstrap 2.3 and 3. 

Please let me know as it might help me make an informed decision before starting to integrate this with my project. 

Thanks

**Comment by Babene03** [comment]
https://github.com/Nodws/bootstrap4-tagsinput

**Comment by vachigaggl** [comment]
I have merged https://github.com/Nodws/bootstrap4-tagsinput with bootstrap-tagsinput/bootstrap-tagsinput here: https://github.com/vachigaggl/bootstrap-tagsinput
