### ISSUE TITLE
Input field too small for tags with wide characters

### ISSUE THREAD

**Issue by cygnil** [bootstrap-tagsinput/bootstrap-tagsinput#70]
It looks like the size attribute of the tag input field grows according to the number of characters in it, but this ends up cutting off some of the tag if it has a few very wide characters (such as M or W). It might be a little clunkier technically, but would it be feasible to copy the text into an invisible element on keyup, measure its width, and then set the CSS width of the tag input box instead of using the size attribute?

**Comment by tim-peterson** [comment]
Yes the `size` attribute is not standard. Would be good to have a percent based to do responsive design.
