### ISSUE TITLE
unhandled exception in tagsinput.js

### ISSUE THREAD

**Issue by Tanveer-Singh** [bootstrap-tagsinput/bootstrap-tagsinput#77]
JavaScript runtime error :object doesn't support property or method
My Code
 $('#typevalues').tagsinput({
                itemValue: 'value',
                itemText: 'text',
                typeahead: {
                    source: function (query) {
                        return $.getJSON('keyword/recipe.json');
                    }
                }
            });

![bootstraptags](https://f.cloud.github.com/assets/1491777/2004634/a99c5b0e-86b7-11e3-943c-b88fcc8ff550.jpg)

**Comment by 0vermind** [comment]
It's sad. With this bug the entire plugin is useless.
